### ISSUE TITLE
Windows 11 ARM not supported

### ISSUE THREAD

**Issue by rerickson1** [robocorp/robotframework-lsp#1010]
**Describe the bug**
```
Activating Robocorp Code extension.
Waiting for Robocorp Code (python) language server to finish activating...
Listening for Robo Tasks Output connections on: {"address":"::","family":"IPv6","port":50363}
Unable to activate Robocorp Code extension because python executable from RCC environment was not provided.
 -- Most common reason is that the environment couldn't be created due to network connectivity issues.
 -- Please fix the error and restart VSCode.
Error getting Python
    Currently only Windows amd64 is supported.
    Error: Currently only Windows amd64 is supported.
    	at downloadRcc (c:\Users\ryan\.vscode\extensions\robocorp.robocorp-code-1.10.0\vscode-client\out\rcc.js:113:19)
    	at $.d (c:\Users\ryan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:141:47980)
    	at $.withProgress (c:\Users\ryan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:141:47843)
    	at Object.withProgress (c:\Users\ryan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:158:31838)
    	at getRccLocation (c:\Users\ryan\.vscode\extensions\robocorp.robocorp-code-1.10.0\vscode-client\out\rcc.js:270:31)
[Error - 12:53:41 PM] Starting client failed
Error: Currently only Windows amd64 is supported.
	at downloadRcc (c:\Users\ryan\.vscode\extensions\robocorp.robocorp-code-1.10.0\vscode-client\out\rcc.js:113:19)
	at $.d (c:\Users\ryan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:141:47980)
	at $.withProgress (c:\Users\ryan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:141:47843)
	at Object.withProgress (c:\Users\ryan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:158:31838)
	at getRccLocation (c:\Users\ryan\.vscode\extensions\robocorp.robocorp-code-1.10.0\vscode-client\out\rcc.js:270:31)
Error initializing Robocorp code.
    Currently only Windows amd64 is supported.
    Error: Currently only Windows amd64 is supported.
    	at downloadRcc (c:\Users\ryan\.vscode\extensions\robocorp.robocorp-code-1.10.0\vscode-client\out\rcc.js:113:19)
    	at $.d (c:\Users\ryan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:141:47980)
    	at $.withProgress (c:\Users\ryan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:141:47843)
    	at Object.withProgress (c:\Users\ryan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:158:31838)
    	at getRccLocation (c:\Users\ryan\.vscode\extensions\robocorp.robocorp-code-1.10.0\vscode-client\out\rcc.js:270:31)
Robocorp Code initialization finished. Took: 0.8s
```

**Expected behavior**
Windows 11 ARM allows for amd64 emulation. Change your extension to use amd64 setup on Window ARM and it should work just fine.

**Versions:**
 - OS:
   Edition	Windows 11 Pro
   Version	22H2
    Installed on	‎30/‎10/‎2023
    OS build	22621.2792
    Experience	Windows Feature Experience Pack 1000.22681.1000.0

 - Robocorp Code Version: 1.10.0
 - Robot Framework Language Server Version: 1.11.0
 - Client Version: VSCode 1.85.0

**Comment by fabioz** [comment]
Unfortunately this is a known (and expected) issue. ARM is not currently supported.

**Comment by rerickson1** [comment]
I know ARM is not supported. On ARM platforms, just use x86 components. Windows 11 ARM has the emulation so X86 binaries will just work.
You just need to change your checks.
