### ISSUE TITLE
BodyRunner.run() missing 1 required positional argument: 'result' 

### ISSUE THREAD

**Issue by zdrizga-nam** [robocorp/robotframework-lsp#1050]
**Describe the bug**
BodyRunner.run() missing 1 required positional argument: 'result' 
'Import' object has no attribute 'parent' 

**To Reproduce**
Click on "Run Interactive Console"

**Expected behavior**
Start the Interactive console and works.

**Screenshots**

**Versions:**
 - OS:  Windows 11
 - Robot Framework Version: Robot Framework 7.0 (Python 3.10.11 on win32)
 - Robot Framework Language Server Version: v1.11.0
 - Client Version: VSCode 1.87.0

**Logs**
ErrorBodyRunner.run() missing 1 required positional argument: 'result' [[-]](vscode-webview://0k9e58amadrfgv1ad2khsaseruo9pn66v131tiqq7oqp1rpiuqpj/index.html?id=e2db7f5d-8ef8-47f0-80cf-46ba76109ceb&origin=9f504294-0234-4078-9d59-f28c755b38ef&swVersion=4&extensionId=robocorp.robotframework-lsp&platform=electron&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=vscode-file%3A%2F%2Fvscode-app#)
Traceback (most recent call last):
  File "c:\Users\zdenekdrizga\.vscode\extensions\robocorp.robotframework-lsp-1.11.0\src\robotframework_ls\vendored\robotframework_interactive\interpreter.py", line 422, in evaluate
    return self._evaluate(code)
  File "c:\Users\zdenekdrizga\.vscode\extensions\robocorp.robotframework-lsp-1.11.0\src\robotframework_ls\vendored\robotframework_interactive\interpreter.py", line 532, in _evaluate
    last_result = facade.run_test_body(context, test, model)
  File "c:\Users\zdenekdrizga\.vscode\extensions\robocorp.robotframework-lsp-1.11.0\src\robotframework_ls\vendored\robotframework_interactive\robotfacade.py", line 135, in run_test_body
    BodyRunner(context, templated=False).run(test.body)
TypeError: BodyRunner.run() missing 1 required positional argument: 'result'

Error'Import' object has no attribute 'parent' [[-]](vscode-webview://0k9e58amadrfgv1ad2khsaseruo9pn66v131tiqq7oqp1rpiuqpj/index.html?id=e2db7f5d-8ef8-47f0-80cf-46ba76109ceb&origin=9f504294-0234-4078-9d59-f28c755b38ef&swVersion=4&extensionId=robocorp.robotframework-lsp&platform=electron&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=vscode-file%3A%2F%2Fvscode-app#)
Traceback (most recent call last):
  File "c:\Users\zdenekdrizga\.vscode\extensions\robocorp.robotframework-lsp-1.11.0\src\robotframework_ls\vendored\robotframework_interactive\interpreter.py", line 582, in _set_source
    element.source = source
AttributeError: can't set attribute 'source'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\zdenekdrizga\.vscode\extensions\robocorp.robotframework-lsp-1.11.0\src\robotframework_ls\vendored\robotframework_interactive\interpreter.py", line 422, in evaluate
    return self._evaluate(code)
  File "c:\Users\zdenekdrizga\.vscode\extensions\robocorp.robotframework-lsp-1.11.0\src\robotframework_ls\vendored\robotframework_interactive\interpreter.py", line 501, in _evaluate
    self._set_source(new_import, source)
  File "c:\Users\zdenekdrizga\.vscode\extensions\robocorp.robotframework-lsp-1.11.0\src\robotframework_ls\vendored\robotframework_interactive\interpreter.py", line 584, in _set_source
    element.parent.source = source
AttributeError: 'Import' object has no attribute 'parent'

**Comment by fabioz** [comment]
See: https://github.com/robocorp/robotframework-lsp/issues/1051

**Comment by fabioz** [comment]
Well, I don't personally have time to do it (in my free time) and Robocorp is also not assigning time for someone to do it... 

-- Robocorp is however willing to assign my time to guide someone on how to do it if someone is willing to make the work to  provide a PR (mainly going through the things that are failing in the ci when used with the `master` branch from Robot Framework).
