### ISSUE TITLE
Visual Studio Code install Robocorp Code extension failed in MacbookPro m3, It seems that the Apple m3 chip is not supported

### ISSUE THREAD

**Issue by sky-silence** [robocorp/robotframework-lsp#1062]
**Describe the bug**
Visual Studio Code install Robocorp Code extension failed in MacbookPro m3

**To Reproduce**
1. install  Robocorp Code in visual studio 
2. output notify Unable to activate robocorp code extension. 

**Expected behavior**
I hope I can successfully install robocorp code locally.
**Screenshots**
![robocorp](https://github.com/robocorp/robotframework-lsp/assets/17306736/b9d695f1-a3b7-41d4-99f7-3b17a307c5b1)

**Versions:**
 - OS: MacBook Pro AppleM3 , macOS Sonoma 14.4
 - Robot Framework Version: 1.20.1
 - VSCode 1.88.0 

**Logs**
`
Activating Robocorp Code extension.
Waiting for Robocorp Code (python) language server to finish activating...
Listening for Robo Tasks Output connections on: {"address":"::","family":"IPv6","port":55889}
ROBOCORP_HOME: /Users/chengzeshan/.robocorp
Executing: /Users/chengzeshan/.vscode/extensions/robocorp.robocorp-code-1.20.1-darwin-arm64/bin/rcc configure diagnostics -j --controller RobocorpCode
Error executing: /Users/chengzeshan/.vscode/extensions/robocorp.robocorp-code-1.20.1-darwin-arm64/bin/rcc configure diagnostics -j --controller RobocorpCode
Error getting RCC diagnostics.
    spawn Unknown system error -86
    Error: spawn Unknown system error -86
        at ChildProcess.spawn (node:internal/child_process:414:11)
        at spawn (node:child_process:799:9)
        at execFile (node:child_process:352:17)
        at t.<computed> (node:electron/js2c/node_init:2:2610)
        at /Users/chengzeshan/.vscode/extensions/robocorp.robocorp-code-1.20.1-darwin-arm64/vscode-client/out/subprocess.js:9:57
        at new Promise (<anonymous>)
        at _execFileAsPromise (/Users/chengzeshan/.vscode/extensions/robocorp.robocorp-code-1.20.1-darwin-arm64/vscode-client/out/subprocess.js:8:12)
        at execFilePromise (/Users/chengzeshan/.vscode/extensions/robocorp.robocorp-code-1.20.1-darwin-arm64/vscode-client/out/subprocess.js:56:22)
        at runConfigDiagnostics (/Users/chengzeshan/.vscode/extensions/robocorp.robocorp-code-1.20.1-darwin-arm64/vscode-client/out/rcc.js:341:75)
        at getLanguageServerPythonInfoUncached (/Users/chengzeshan/.vscode/extensions/robocorp.robocorp-code-1.20.1-darwin-arm64/vscode-client/out/extensionCreateEnv.js:515:69)
        at async getLanguageServerPythonInfo (/Users/chengzeshan/.vscode/extensions/robocorp.robocorp-code-1.20.1-darwin-arm64/vscode-client/out/extension.js:656:28)
        at async serverOptions (/Users/chengzeshan/.vscode/extensions/robocorp.robocorp-code-1.20.1-darwin-arm64/vscode-client/out/extension.js:94:28)

Took 0.0s to obtain diagnostics.
Unable to activate Robocorp Code extension because python executable from RCC environment was not provided.
 -- Most common reason is that the environment couldn't be created due to network connectivity issues.
 -- Please fix the error and restart VSCode.
Error getting Python
    Cannot read properties of undefined (reading 'stdout')
    TypeError: Cannot read properties of undefined (reading 'stdout')
        at runConfigDiagnostics (/Users/chengzeshan/.vscode/extensions/robocorp.robocorp-code-1.20.1-darwin-arm64/vscode-client/out/rcc.js:374:38)
        at async basicValidations (/Users/chengzeshan/.vscode/extensions/robocorp.robocorp-code-1.20.1-darwin-arm64/vscode-client/out/extensionCreateEnv.js:251:26)
        at async createDefaultEnv (/Users/chengzeshan/.vscode/extensions/robocorp.robocorp-code-1.20.1-darwin-arm64/vscode-client/out/extensionCreateEnv.js:365:36)
        at async /Users/chengzeshan/.vscode/extensions/robocorp.robocorp-code-1.20.1-darwin-arm64/vscode-client/out/extensionCreateEnv.js:539:16
[Error - 11:37:50] Starting client failed
TypeError: Cannot read properties of undefined (reading 'stdout')
    at runConfigDiagnostics (/Users/chengzeshan/.vscode/extensions/robocorp.robocorp-code-1.20.1-darwin-arm64/vscode-client/out/rcc.js:374:38)
    at async basicValidations (/Users/chengzeshan/.vscode/extensions/robocorp.robocorp-code-1.20.1-darwin-arm64/vscode-client/out/extensionCreateEnv.js:251:26)
    at async createDefaultEnv (/Users/chengzeshan/.vscode/extensions/robocorp.robocorp-code-1.20.1-darwin-arm64/vscode-client/out/extensionCreateEnv.js:365:36)
    at async /Users/chengzeshan/.vscode/extensions/robocorp.robocorp-code-1.20.1-darwin-arm64/vscode-client/out/extensionCreateEnv.js:539:16
Error initializing Robocorp code.
    Cannot read properties of undefined (reading 'stdout')
    TypeError: Cannot read properties of undefined (reading 'stdout')
        at runConfigDiagnostics (/Users/chengzeshan/.vscode/extensions/robocorp.robocorp-code-1.20.1-darwin-arm64/vscode-client/out/rcc.js:374:38)
        at async basicValidations (/Users/chengzeshan/.vscode/extensions/robocorp.robocorp-code-1.20.1-darwin-arm64/vscode-client/out/extensionCreateEnv.js:251:26)
        at async createDefaultEnv (/Users/chengzeshan/.vscode/extensions/robocorp.robocorp-code-1.20.1-darwin-arm64/vscode-client/out/extensionCreateEnv.js:365:36)
        at async /Users/chengzeshan/.vscode/extensions/robocorp.robocorp-code-1.20.1-darwin-arm64/vscode-client/out/extensionCreateEnv.js:539:16
Robocorp Code initialization finished. Took: 0.0s
Error executing: /Users/chengzeshan/.vscode/extensions/robocorp.robocorp-code-1.20.1-darwin-arm64/bin/rcc feedback metric -t vscode -n vscode.code.error -v RCC_DIAGNOSTICS
Error executing: /Users/chengzeshan/.vscode/extensions/robocorp.robocorp-code-1.20.1-darwin-arm64/bin/rcc feedback metric -t vscode -n vscode.code.error -v INIT_PYTHON_ERR
Error executing: /Users/chengzeshan/.vscode/extensions/robocorp.robocorp-code-1.20.1-darwin-arm64/bin/rcc feedback metric -t vscode -n vscode.code.error -v ERROR_INITIALIZING_ROBOCORP_CODE_LANG_SERVER
Error getting children
    command 'robocorp.getLinkedAccountInfo.internal' not found
    Error: command 'robocorp.getLinkedAccountInfo.internal' not found
        at S.n (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1602:23049)
        at S.executeCommand (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1602:22978)
Error executing: /Users/chengzeshan/.vscode/extensions/robocorp.robocorp-code-1.20.1-darwin-arm64/bin/rcc feedback metric -t vscode -n vscode.code.error -v VIEWS_CLOUD_COMPUTE_ROOTS
Error resolving interpreter.
    command 'robocorp.resolveInterpreter' not found
    Error: command 'robocorp.resolveInterpreter' not found
        at S.n (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1602:23049)
        at S.executeCommand (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1602:22978)
Error executing: /Users/chengzeshan/.vscode/extensions/robocorp.robocorp-code-1.20.1-darwin-arm64/bin/rcc feedback metric -t vscode -n vscode.code.error -v ACT_RESOLVE_INTERPRETER
`

**Comment by fabioz** [comment]
Right now it needs to have Rosetta installed and configured to work... Can you make sure it's installed and configured in your machine?

**Comment by kariharju** [comment]
This issue has been moved <a href="https://github.com/Sema4AI/vscode-extension/issues/44">here</a>, under <a href=https://github.com/Sema4AI/vscode-extension>Sema4AI/vscode-extension</a> repository.
