### ISSUE TITLE
Unable to activate Robocorp Code extension

### ISSUE THREAD

**Issue by DANCY-2218** [robocorp/robotframework-lsp#1081]
output as below:

Activating Robocorp Code extension.
Waiting for Robocorp Code (python) language server to finish activating...
Listening for Robo Tasks Output connections on: {"address":"::","family":"IPv6","port":55272}
ROBOCORP_HOME: C:\Users\Dancy.Liu\AppData\Local\robocorp
Executing: c:\Users\Dancy.Liu\.vscode\extensions\robocorp.robocorp-code-1.22.3-win32-x64\bin\rcc.exe configure diagnostics -j --controller RobocorpCode
Windows long paths support enabled
Error executing: c:\Users\Dancy.Liu\.vscode\extensions\robocorp.robocorp-code-1.22.3-win32-x64\bin\rcc.exe configure diagnostics -j --controller RobocorpCode
Error: Error: Command failed: c:\Users\Dancy.Liu\.vscode\extensions\robocorp.robocorp-code-1.22.3-win32-x64\bin\rcc.exe configure diagnostics -j --controller RobocorpCode
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0xc0004950f8 addr=0xa2c699 pc=0xc1bb83]

goroutine 1 [running]:
main.ExitProtection()
	/home/runner/work/rcc-pipeline/rcc-pipeline/rcc/cmd/rcc/main.go:88 +0xce
panic({0xcb6f40, 0x15358d0})
	/opt/hostedtoolcache/go/1.20.14/x64/src/runtime/panic.go:884 +0x213
github.com/robocorp/rcc/operations.tlsCheckHost({0xc0000286c0, 0x12}, 0xc000495938?)
	/home/runner/work/rcc-pipeline/rcc-pipeline/rcc/operations/tlscheck.go:104 +0x103
github.com/robocorp/rcc/operations.runDiagnostics(0x0)
	/home/runner/work/rcc-pipeline/rcc-pipeline/rcc/operations/diagnostics.go:183 +0x360d
github.com/robocorp/rcc/operations.ProduceDiagnostics({0x0?, 0x0?}, {0x0, 0x0}, 0x1, 0x0?, 0x0?)
	/home/runner/work/rcc-pipeline/rcc-pipeline/rcc/operations/diagnostics.go:627 +0xba
github.com/robocorp/rcc/cmd.glob..func16(0x1546b40?, {0xd2ea9a?, 0x3?, 0x3?})
	/home/runner/work/rcc-pipeline/rcc-pipeline/rcc/cmd/diagnostics.go:26 +0xd6
github.com/spf13/cobra.(*Command).execute(0x1546b40, {0xc0000b8420, 0x3, 0x3})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x15448c0)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/robocorp/rcc/cmd.Execute()
	/home/runner/work/rcc-pipeline/rcc-pipeline/rcc/cmd/root.go:99 +0xb1
main.main()
	/home/runner/work/rcc-pipeline/rcc-pipeline/rcc/cmd/rcc/main.go:160 +0x346

Error message: Command failed: c:\Users\Dancy.Liu\.vscode\extensions\robocorp.robocorp-code-1.22.3-win32-x64\bin\rcc.exe configure diagnostics -j --controller RobocorpCode
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0xc0004950f8 addr=0xa2c699 pc=0xc1bb83]

goroutine 1 [running]:
main.ExitProtection()
	/home/runner/work/rcc-pipeline/rcc-pipeline/rcc/cmd/rcc/main.go:88 +0xce
panic({0xcb6f40, 0x15358d0})
	/opt/hostedtoolcache/go/1.20.14/x64/src/runtime/panic.go:884 +0x213
github.com/robocorp/rcc/operations.tlsCheckHost({0xc0000286c0, 0x12}, 0xc000495938?)
	/home/runner/work/rcc-pipeline/rcc-pipeline/rcc/operations/tlscheck.go:104 +0x103
github.com/robocorp/rcc/operations.runDiagnostics(0x0)
	/home/runner/work/rcc-pipeline/rcc-pipeline/rcc/operations/diagnostics.go:183 +0x360d
github.com/robocorp/rcc/operations.ProduceDiagnostics({0x0?, 0x0?}, {0x0, 0x0}, 0x1, 0x0?, 0x0?)
	/home/runner/work/rcc-pipeline/rcc-pipeline/rcc/operations/diagnostics.go:627 +0xba
github.com/robocorp/rcc/cmd.glob..func16(0x1546b40?, {0xd2ea9a?, 0x3?, 0x3?})
	/home/runner/work/rcc-pipeline/rcc-pipeline/rcc/cmd/diagnostics.go:26 +0xd6
github.com/spf13/cobra.(*Command).execute(0x1546b40, {0xc0000b8420, 0x3, 0x3})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x15448c0)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/robocorp/rcc/cmd.Execute()
	/home/runner/work/rcc-pipeline/rcc-pipeline/rcc/cmd/root.go:99 +0xb1
main.main()
	/home/runner/work/rcc-pipeline/rcc-pipeline/rcc/cmd/rcc/main.go:160 +0x346

Error code: 2
Error name: Error
Stderr: panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0xc0004950f8 addr=0xa2c699 pc=0xc1bb83]

goroutine 1 [running]:
main.ExitProtection()
	/home/runner/work/rcc-pipeline/rcc-pipeline/rcc/cmd/rcc/main.go:88 +0xce
panic({0xcb6f40, 0x15358d0})
	/opt/hostedtoolcache/go/1.20.14/x64/src/runtime/panic.go:884 +0x213
github.com/robocorp/rcc/operations.tlsCheckHost({0xc0000286c0, 0x12}, 0xc000495938?)
	/home/runner/work/rcc-pipeline/rcc-pipeline/rcc/operations/tlscheck.go:104 +0x103
github.com/robocorp/rcc/operations.runDiagnostics(0x0)
	/home/runner/work/rcc-pipeline/rcc-pipeline/rcc/operations/diagnostics.go:183 +0x360d
github.com/robocorp/rcc/operations.ProduceDiagnostics({0x0?, 0x0?}, {0x0, 0x0}, 0x1, 0x0?, 0x0?)
	/home/runner/work/rcc-pipeline/rcc-pipeline/rcc/operations/diagnostics.go:627 +0xba
github.com/robocorp/rcc/cmd.glob..func16(0x1546b40?, {0xd2ea9a?, 0x3?, 0x3?})
	/home/runner/work/rcc-pipeline/rcc-pipeline/rcc/cmd/diagnostics.go:26 +0xd6
github.com/spf13/cobra.(*Command).execute(0x1546b40, {0xc0000b8420, 0x3, 0x3})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x15448c0)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/robocorp/rcc/cmd.Execute()
	/home/runner/work/rcc-pipeline/rcc-pipeline/rcc/cmd/root.go:99 +0xb1
main.main()
	/home/runner/work/rcc-pipeline/rcc-pipeline/rcc/cmd/rcc/main.go:160 +0x346

Error getting RCC diagnostics.

Took 5.5s to obtain diagnostics.
Unable to activate Robocorp Code extension because python executable from RCC environment was not provided.
 -- Most common reason is that the environment couldn't be created due to network connectivity issues.
 -- Please fix the error and restart VSCode.
Error getting Python
    Cannot read properties of undefined (reading 'stdout')
    TypeError: Cannot read properties of undefined (reading 'stdout')
    	at runConfigDiagnostics (c:\Users\Dancy.Liu\.vscode\extensions\robocorp.robocorp-code-1.22.3-win32-x64\vscode-client\out\rcc.js:374:38)
    	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    	at async basicValidations (c:\Users\Dancy.Liu\.vscode\extensions\robocorp.robocorp-code-1.22.3-win32-x64\vscode-client\out\extensionCreateEnv.js:251:26)
    	at async createDefaultEnv (c:\Users\Dancy.Liu\.vscode\extensions\robocorp.robocorp-code-1.22.3-win32-x64\vscode-client\out\extensionCreateEnv.js:365:36)
    	at async c:\Users\Dancy.Liu\.vscode\extensions\robocorp.robocorp-code-1.22.3-win32-x64\vscode-client\out\extensionCreateEnv.js:539:16
[Error - 4:29:18 PM] Starting client failed
TypeError: Cannot read properties of undefined (reading 'stdout')
	at runConfigDiagnostics (c:\Users\Dancy.Liu\.vscode\extensions\robocorp.robocorp-code-1.22.3-win32-x64\vscode-client\out\rcc.js:374:38)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async basicValidations (c:\Users\Dancy.Liu\.vscode\extensions\robocorp.robocorp-code-1.22.3-win32-x64\vscode-client\out\extensionCreateEnv.js:251:26)
	at async createDefaultEnv (c:\Users\Dancy.Liu\.vscode\extensions\robocorp.robocorp-code-1.22.3-win32-x64\vscode-client\out\extensionCreateEnv.js:365:36)
	at async c:\Users\Dancy.Liu\.vscode\extensions\robocorp.robocorp-code-1.22.3-win32-x64\vscode-client\out\extensionCreateEnv.js:539:16
Error initializing Robocorp code.
    Cannot read properties of undefined (reading 'stdout')
    TypeError: Cannot read properties of undefined (reading 'stdout')
    	at runConfigDiagnostics (c:\Users\Dancy.Liu\.vscode\extensions\robocorp.robocorp-code-1.22.3-win32-x64\vscode-client\out\rcc.js:374:38)
    	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    	at async basicValidations (c:\Users\Dancy.Liu\.vscode\extensions\robocorp.robocorp-code-1.22.3-win32-x64\vscode-client\out\extensionCreateEnv.js:251:26)
    	at async createDefaultEnv (c:\Users\Dancy.Liu\.vscode\extensions\robocorp.robocorp-code-1.22.3-win32-x64\vscode-client\out\extensionCreateEnv.js:365:36)
    	at async c:\Users\Dancy.Liu\.vscode\extensions\robocorp.robocorp-code-1.22.3-win32-x64\vscode-client\out\extensionCreateEnv.js:539:16
Robocorp Code initialization finished. Took: 5.5s
Executing: c:\Users\Dancy.Liu\.vscode\extensions\robocorp.robocorp-code-1.22.3-win32-x64\bin\rcc.exe holotree list --json --controller RobocorpCode
Error resolving interpreter.
    command 'robocorp.resolveInterpreter' not found
    Error: command 'robocorp.resolveInterpreter' not found
        at a6e.n (vscode-file://vscode-app/c:/Users/Dancy.Liu/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1299:1341)
        at a6e.executeCommand (vscode-file://vscode-app/c:/Users/Dancy.Liu/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1299:1273)
{}
Stopped Robot Framework Language Server. Took: 0.0s
Error restarting Robocorp Code
    Cannot read properties of undefined (reading 'stdout')
    TypeError: Cannot read properties of undefined (reading 'stdout')
    	at runConfigDiagnostics (c:\Users\Dancy.Liu\.vscode\extensions\robocorp.robocorp-code-1.22.3-win32-x64\vscode-client\out\rcc.js:374:38)
    	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    	at async basicValidations (c:\Users\Dancy.Liu\.vscode\extensions\robocorp.robocorp-code-1.22.3-win32-x64\vscode-client\out\extensionCreateEnv.js:251:26)
    	at async createDefaultEnv (c:\Users\Dancy.Liu\.vscode\extensions\robocorp.robocorp-code-1.22.3-win32-x64\vscode-client\out\extensionCreateEnv.js:365:36)
    	at async c:\Users\Dancy.Liu\.vscode\extensions\robocorp.robocorp-code-1.22.3-win32-x64\vscode-client\out\extensionCreateEnv.js:539:16
Error resolving interpreter.
    command 'robocorp.resolveInterpreter' not found
    Error: command 'robocorp.resolveInterpreter' not found
        at a6e.n (vscode-file://vscode-app/c:/Users/Dancy.Liu/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1299:1341)
        at a6e.executeCommand (vscode-file://vscode-app/c:/Users/Dancy.Liu/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1299:1273)

**Comment by fabioz** [comment]
It seems there was some issue bootstrapping the environment with the latest `rcc`.

The `Robocorp Code` extension is currently actually deprecated and all new development/support is done through the `Sema4.ai` vscode extension.

Can you remove `Robocorp Code` and install `Sema4.ai` to see if it works for you?
