### ISSUE TITLE
Autocomplete doesn't work on Windows 10

### ISSUE THREAD

**Issue by seifip** [robocorp/robotframework-lsp#125]
**Describe the bug**
Installed Robot Framework LS extensions in VSCde. Autocomplete doens't work. Tried disabling all other extensions, didn't help.

**To Reproduce**
Install Robot Framework LS in VSCode, Open a .robot file, try typing Click, or Whait until, and press Ctrl+Space.

**Expected behavior**
Autocomplete (Click button, Click link... Wait until element visible, Wait until element exists etc.)

**Versions:**
 - OS: Windows 10
 - Robot Framework Version 3.2.1.
 - Robot Framework Language Server Version 0.3.1
 - Client Version VSCode 1.47.3

**Logs**
[logs.zip](https://github.com/robocorp/robotframework-lsp/files/5016468/logs.zip)

[settings.zip](https://github.com/robocorp/robotframework-lsp/files/5016487/settings.zip)

**Comment by fabioz** [comment]
Hello Philip, thanks for the report.

I can see in the log that it's not being able to generate completions for some of the libraries you have (which I believe are the ones you want completion for).

In particular:

```
Generating libspec for: RPA.Browser.
Cwd:c:\Users\phili\Documents\GitHub\white-rabbit-japan\rpa-rabot\resources
Command line:
C:\Users\phili\anaconda3\python.exe -m robot.libdoc --format XML:HTML -P c:\Users\phili\Documents\GitHub\white-rabbit-japan\rpa-rabot\resources RPA.Browser C:\Users\phili\.robotframework-ls\specs\5ccafb0d_3.2.1\user\RPA.Browser.libspec


Generating libspec for: RabotUtils.
Cwd:c:\Users\phili\Documents\GitHub\white-rabbit-japan\rpa-rabot\resources
Command line:
C:\Users\phili\anaconda3\python.exe -m robot.libdoc --format XML:HTML -P c:\Users\phili\Documents\GitHub\white-rabbit-japan\rpa-rabot\resources RabotUtils C:\Users\phili\.robotframework-ls\specs\5ccafb0d_3.2.1\user\RabotUtils.libspec

Generating libspec for: RobotNotifications.
Cwd:c:\Users\phili\Documents\GitHub\white-rabbit-japan\rpa-rabot\resources
Command line:
C:\Users\phili\anaconda3\python.exe -m robot.libdoc --format XML:HTML -P c:\Users\phili\Documents\GitHub\white-rabbit-japan\rpa-rabot\resources RobotNotifications C:\Users\phili\.robotframework-ls\specs\5ccafb0d_3.2.1\user\RobotNotifications.libspec
```

So, you need to have those libraries installed in the same python executable you're using for the language server to be able to provide completions for them.

**Comment by seifip** [comment]
I've made sure I have these installed in conda... now the python server is crashing on start:


```
Getting language server Python executable.
Starting RobotFramework Language Server with args: C:\Users\phili\AppData\Local\robocorp\RobocodeLab\data\conda\python.exe,-u,c:\Users\phili\.vscode\extensions\robocorptech.robotframework-lsp-0.3.1\src\robotframework_ls\__main__.py,-vv,--log-file=C:\WebDriver\robotframework_ls.log
Waiting for RobotFramework (python) Language Server to finish activating...
usage: __main__.py [-h] [--tcp] [--host HOST] [--port PORT]
                   [--log-file LOG_FILE] [-v]
__main__.py: error: argument -v/--verbose: ignored explicit argument ',--log-file=C:\\WebDriver\\robotframework_ls.log'
Traceback (most recent call last):
  File "C:\Users\phili\AppData\Local\robocorp\RobocodeLab\data\conda\lib\argparse.py", line 1787, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\Users\phili\AppData\Local\robocorp\RobocodeLab\data\conda\lib\argparse.py", line 1993, in _parse_known_args
    start_index = consume_optional(start_index)
  File "C:\Users\phili\AppData\Local\robocorp\RobocodeLab\data\conda\lib\argparse.py", line 1901, in consume_optional
    raise ArgumentError(action, msg % explicit_arg)
argparse.ArgumentError: argument -v/--verbose: ignored explicit argument ',--log-file=C:\\WebDriver\\robotframework_ls.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\phili\.vscode\extensions\robocorptech.robotframework-lsp-0.3.1\src\robotframework_ls\__main__.py", line 121, in <module>
    main()
  File "c:\Users\phili\.vscode\extensions\robocorptech.robotframework-lsp-0.3.1\src\robotframework_ls\__main__.py", line 101, in main
    args = parser.parse_args(args=original_args)
  File "C:\Users\phili\AppData\Local\robocorp\RobocodeLab\data\conda\lib\argparse.py", line 1755, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "C:\Users\phili\AppData\Local\robocorp\RobocodeLab\data\conda\lib\argparse.py", line 1794, in parse_known_args
    self.error(str(err))
  File "C:\Users\phili\AppData\Local\robocorp\RobocodeLab\data\conda\lib\argparse.py", line 2507, in error
    self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
  File "C:\Users\phili\AppData\Local\robocorp\RobocodeLab\data\conda\lib\argparse.py", line 2494, in exit
    _sys.exit(status)
SystemExit: 2
[Info  - 23:18:15] Connection to server got closed. Server will restart.
usage: __main__.py [-h] [--tcp] [--host HOST] [--port PORT]
                   [--log-file LOG_FILE] [-v]
__main__.py: error: argument -v/--verbose: ignored explicit argument ',--log-file=C:\\WebDriver\\robotframework_ls.log'
Traceback (most recent call last):
  File "C:\Users\phili\AppData\Local\robocorp\RobocodeLab\data\conda\lib\argparse.py", line 1787, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\Users\phili\AppData\Local\robocorp\RobocodeLab\data\conda\lib\argparse.py", line 1993, in _parse_known_args
    start_index = consume_optional(start_index)
  File "C:\Users\phili\AppData\Local\robocorp\RobocodeLab\data\conda\lib\argparse.py", line 1901, in consume_optional
    raise ArgumentError(action, msg % explicit_arg)
argparse.ArgumentError: argument -v/--verbose: ignored explicit argument ',--log-file=C:\\WebDriver\\robotframework_ls.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\phili\.vscode\extensions\robocorptech.robotframework-lsp-0.3.1\src\robotframework_ls\__main__.py", line 121, in <module>
    main()
  File "c:\Users\phili\.vscode\extensions\robocorptech.robotframework-lsp-0.3.1\src\robotframework_ls\__main__.py", line 101, in main
    args = parser.parse_args(args=original_args)
  File "C:\Users\phili\AppData\Local\robocorp\RobocodeLab\data\conda\lib\argparse.py", line 1755, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "C:\Users\phili\AppData\Local\robocorp\RobocodeLab\data\conda\lib\argparse.py", line 1794, in parse_known_args
    self.error(str(err))
  File "C:\Users\phili\AppData\Local\robocorp\RobocodeLab\data\conda\lib\argparse.py", line 2507, in error
    self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
  File "C:\Users\phili\AppData\Local\robocorp\RobocodeLab\data\conda\lib\argparse.py", line 2494, in exit
    _sys.exit(status)
SystemExit: 2
[Info  - 23:18:15] Connection to server got closed. Server will restart.
usage: __main__.py [-h] [--tcp] [--host HOST] [--port PORT]
                   [--log-file LOG_FILE] [-v]
__main__.py: error: argument -v/--verbose: ignored explicit argument ',--log-file=C:\\WebDriver\\robotframework_ls.log'
Traceback (most recent call last):
  File "C:\Users\phili\AppData\Local\robocorp\RobocodeLab\data\conda\lib\argparse.py", line 1787, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\Users\phili\AppData\Local\robocorp\RobocodeLab\data\conda\lib\argparse.py", line 1993, in _parse_known_args
    start_index = consume_optional(start_index)
  File "C:\Users\phili\AppData\Local\robocorp\RobocodeLab\data\conda\lib\argparse.py", line 1901, in consume_optional
    raise ArgumentError(action, msg % explicit_arg)
argparse.ArgumentError: argument -v/--verbose: ignored explicit argument ',--log-file=C:\\WebDriver\\robotframework_ls.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\phili\.vscode\extensions\robocorptech.robotframework-lsp-0.3.1\src\robotframework_ls\__main__.py", line 121, in <module>
    main()
  File "c:\Users\phili\.vscode\extensions\robocorptech.robotframework-lsp-0.3.1\src\robotframework_ls\__main__.py", line 101, in main
    args = parser.parse_args(args=original_args)
  File "C:\Users\phili\AppData\Local\robocorp\RobocodeLab\data\conda\lib\argparse.py", line 1755, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "C:\Users\phili\AppData\Local\robocorp\RobocodeLab\data\conda\lib\argparse.py", line 1794, in parse_known_args
    self.error(str(err))
  File "C:\Users\phili\AppData\Local\robocorp\RobocodeLab\data\conda\lib\argparse.py", line 2507, in error
    self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
  File "C:\Users\phili\AppData\Local\robocorp\RobocodeLab\data\conda\lib\argparse.py", line 2494, in exit
    _sys.exit(status)
SystemExit: 2
[Info  - 23:18:15] Connection to server got closed. Server will restart.
usage: __main__.py [-h] [--tcp] [--host HOST] [--port PORT]
                   [--log-file LOG_FILE] [-v]
__main__.py: error: argument -v/--verbose: ignored explicit argument ',--log-file=C:\\WebDriver\\robotframework_ls.log'
Traceback (most recent call last):
  File "C:\Users\phili\AppData\Local\robocorp\RobocodeLab\data\conda\lib\argparse.py", line 1787, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\Users\phili\AppData\Local\robocorp\RobocodeLab\data\conda\lib\argparse.py", line 1993, in _parse_known_args
    start_index = consume_optional(start_index)
  File "C:\Users\phili\AppData\Local\robocorp\RobocodeLab\data\conda\lib\argparse.py", line 1901, in consume_optional
    raise ArgumentError(action, msg % explicit_arg)
argparse.ArgumentError: argument -v/--verbose: ignored explicit argument ',--log-file=C:\\WebDriver\\robotframework_ls.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\phili\.vscode\extensions\robocorptech.robotframework-lsp-0.3.1\src\robotframework_ls\__main__.py", line 121, in <module>
    main()
  File "c:\Users\phili\.vscode\extensions\robocorptech.robotframework-lsp-0.3.1\src\robotframework_ls\__main__.py", line 101, in main
    args = parser.parse_args(args=original_args)
  File "C:\Users\phili\AppData\Local\robocorp\RobocodeLab\data\conda\lib\argparse.py", line 1755, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "C:\Users\phili\AppData\Local\robocorp\RobocodeLab\data\conda\lib\argparse.py", line 1794, in parse_known_args
    self.error(str(err))
  File "C:\Users\phili\AppData\Local\robocorp\RobocodeLab\data\conda\lib\argparse.py", line 2507, in error
    self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
  File "C:\Users\phili\AppData\Local\robocorp\RobocodeLab\data\conda\lib\argparse.py", line 2494, in exit
    _sys.exit(status)
SystemExit: 2
[Info  - 23:18:15] Connection to server got closed. Server will restart.
usage: __main__.py [-h] [--tcp] [--host HOST] [--port PORT]
                   [--log-file LOG_FILE] [-v]
__main__.py: error: argument -v/--verbose: ignored explicit argument ',--log-file=C:\\WebDriver\\robotframework_ls.log'
Traceback (most recent call last):
  File "C:\Users\phili\AppData\Local\robocorp\RobocodeLab\data\conda\lib\argparse.py", line 1787, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\Users\phili\AppData\Local\robocorp\RobocodeLab\data\conda\lib\argparse.py", line 1993, in _parse_known_args
    start_index = consume_optional(start_index)
  File "C:\Users\phili\AppData\Local\robocorp\RobocodeLab\data\conda\lib\argparse.py", line 1901, in consume_optional
    raise ArgumentError(action, msg % explicit_arg)
argparse.ArgumentError: argument -v/--verbose: ignored explicit argument ',--log-file=C:\\WebDriver\\robotframework_ls.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\phili\.vscode\extensions\robocorptech.robotframework-lsp-0.3.1\src\robotframework_ls\__main__.py", line 121, in <module>
    main()
  File "c:\Users\phili\.vscode\extensions\robocorptech.robotframework-lsp-0.3.1\src\robotframework_ls\__main__.py", line 101, in main
    args = parser.parse_args(args=original_args)
  File "C:\Users\phili\AppData\Local\robocorp\RobocodeLab\data\conda\lib\argparse.py", line 1755, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "C:\Users\phili\AppData\Local\robocorp\RobocodeLab\data\conda\lib\argparse.py", line 1794, in parse_known_args
    self.error(str(err))
  File "C:\Users\phili\AppData\Local\robocorp\RobocodeLab\data\conda\lib\argparse.py", line 2507, in error
    self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
  File "C:\Users\phili\AppData\Local\robocorp\RobocodeLab\data\conda\lib\argparse.py", line 2494, in exit
    _sys.exit(status)
SystemExit: 2
[Error - 23:18:16] Connection to server got closed. Server will not be restarted.
```

**Comment by seifip** [comment]
I finally got it working, thank you!

That said, the autocomplete is extremely slow. It takes 5-10s for the suggestions to load on Ctrl+Space, much, much longer than autocomplete for other languages, or within Robocode Lab.

Is this normal?

**Comment by fabioz** [comment]
> That said, the autocomplete is extremely slow. It takes 5-10s for the suggestions to load on Ctrl+Space, much, much longer than autocomplete for other languages, or within Robocode Lab.
> 
> Is this normal?

No, that's not normal... have you disabled the logging afterwards?

-- i.e.: The logging may make things slow.

If it's still slow, even without the logging, please create an issue to investigate that.
