### ISSUE TITLE
Language server 0.6.x does not anymore work with PyCHarm

### ISSUE THREAD

**Issue by aaltat** [robocorp/robotframework-lsp#205]
**Describe the bug**
Language server 0.6.0 and 0.6.1 does not anymore work with PyCharm, but the 0.5.0 works normally.

**To Reproduce**
Configure LSP with with RF [Forum instructions](https://forum.robotframework.org/t/pycharm-with-lsp/161). Open PyCharm and wait it start up properly. Open existing .robot file and then automatic completion does not work. 

**Expected behavior**
Did expect automatic keyword completion wot work, but example SeleniumLibrary or BuiltIn keywords are not visible:

**Screenshots**
![image](https://user-images.githubusercontent.com/2665023/100667133-c59acc00-3362-11eb-8563-93eeb1d35217.png)

**Versions:**
 - OS: Windows 10
 - Robot Framework Version  3.2.2
 - Robot Framework Language Server Version 0.6.0 and 0.6.1
 - Client Version PyCharm 2020.2.4

**Logs**
In the logs I see this:
```
lsp: 2020-11-30 23:14:12 UTC pid: 3496 - MainThread - DEBUG - robotframework_ls.__main__
Arguments: ['-vv', '--log-file=C:\\workspace\\advanced-seleniumlibrary-workshop\\lsp\\debug\\robotframework_ls.log']

lsp: 2020-11-30 23:14:12 UTC pid: 3496 - MainThread - DEBUG - robotframework_ls.__main__
Python: 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)] - lsp: 0.6.1 - platform: win32 - sys.prefix: c:\workspace\advanced-seleniumlibrary-workshop\.venv - sys.executable: c:\workspace\advanced-seleniumlibrary-workshop\.venv\scripts\python.exe

lsp: 2020-11-30 23:14:12 UTC pid: 3496 - MainThread - INFO - robocorp_ls_core.python_ls
Starting RobotFrameworkLanguageServer IO language server. pid: 3496

lsp: 2020-11-30 23:14:12 UTC pid: 3496 - MainThread - DEBUG - robotframework_ls.robotframework_ls_impl
Cache dir: C:\Users\gtn-admin\.robotframework-ls\.cache

lsp: 2020-11-30 23:14:13 UTC pid: 3496 - MainThread - DEBUG - robocorp_ls_core.jsonrpc.streams
Read: {"jsonrpc":"2.0","id":"1","method":"initialize","params":{"processId":null,"rootUri":"file:///C:/workspace/advanced-seleniumlibrary-workshop/","capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true},"didChangeConfiguration":{},"didChangeWatchedFiles":{"dynamicRegistration":true},"symbol":{},"executeCommand":{},"workspaceFolders":false,"configuration":true},"textDocument":{"synchronization":{"willSave":true,"willSaveWaitUntil":true,"didSave":true},"completion":{"completionItem":{"snippetSupport":true}},"hover":{},"signatureHelp":{},"references":{},"documentHighlight":{},"formatting":{},"rangeFormatting":{},"onTypeFormatting":{},"definition":{},"codeAction":{},"rename":{"prepareSupport":true,"dynamicRegistration":false},"semanticHighlightingCapabilities":{"semanticHighlighting":false}}}}}

lsp: 2020-11-30 23:14:13 UTC pid: 3496 - MainThread - DEBUG - robocorp_ls_core.jsonrpc.endpoint
Handling request from client {'jsonrpc': '2.0', 'id': '1', 'method': 'initialize', 'params': {'processId': None, 'rootUri': 'file:///C:/workspace/advanced-seleniumlibrary-workshop/', 'capabilities': {'workspace': {'applyEdit': True, 'workspaceEdit': {'documentChanges': True}, 'didChangeConfiguration': {}, 'didChangeWatchedFiles': {'dynamicRegistration': True}, 'symbol': {}, 'executeCommand': {}, 'workspaceFolders': False, 'configuration': True}, 'textDocument': {'synchronization': {'willSave': True, 'willSaveWaitUntil': True, 'didSave': True}, 'completion': {'completionItem': {'snippetSupport': True}}, 'hover': {}, 'signatureHelp': {}, 'references': {}, 'documentHighlight': {}, 'formatting': {}, 'rangeFormatting': {}, 'onTypeFormatting': {}, 'definition': {}, 'codeAction': {}, 'rename': {'prepareSupport': True, 'dynamicRegistration': False}, 'semanticHighlightingCapabilities': {'semanticHighlighting': False}}}}}

lsp: 2020-11-30 23:14:13 UTC pid: 3496 - MainThread - DEBUG - robocorp_ls_core.python_ls
Language server initialized with:
    processId: None
    rootUri: file:///C:/workspace/advanced-seleniumlibrary-workshop/
    rootPath: None
    initializationOptions: None
    workspaceFolders: None

lsp: 2020-11-30 23:14:13 UTC pid: 3496 - MainThread - INFO - robotframework_ls.robotframework_ls_impl
Server capabilities: {'codeActionProvider': False, 'completionProvider': {'resolveProvider': False}, 'documentFormattingProvider': True, 'documentHighlightProvider': False, 'documentRangeFormattingProvider': False, 'documentSymbolProvider': False, 'definitionProvider': True, 'executeCommandProvider': {'commands': ['robot.addPluginsDir', 'robot.resolveInterpreter']}, 'hoverProvider': False, 'referencesProvider': False, 'renameProvider': False, 'foldingRangeProvider': False, 'signatureHelpProvider': {'triggerCharacters': []}, 'textDocumentSync': {'change': 2, 'save': {'includeText': False}, 'openClose': True}, 'workspace': {'workspaceFolders': {'supported': True, 'changeNotifications': True}}, 'workspaceSymbolProvider': {'workDoneProgress': False}}

lsp: 2020-11-30 23:14:13 UTC pid: 3496 - MainThread - DEBUG - robocorp_ls_core.jsonrpc.endpoint
Got result from synchronous request handler (in 0.00s): {'capabilities': {'codeActionProvider': False, 'completionProvider': {'resolveProvider': False}, 'documentFormattingProvider': True, 'documentHighlightProvider': False, 'documentRangeFormattingProvider': False, 'documentSymbolProvider': False, 'definitionProvider': True, 'executeCommandProvider': {'commands': ['robot.addPluginsDir', 'robot.resolveInterpreter']}, 'hoverProvider': False, 'referencesProvider': False, 'renameProvider': False, 'foldingRangeProvider': False, 'signatureHelpProvider': {'triggerCharacters': []}, 'textDocumentSync': {'change': 2, 'save': {'includeText': False}, 'openClose': True}, 'workspace': {'workspaceFolders': {'supported': True, 'changeNotifications': True}}, 'workspaceSymbolProvider': {'workDoneProgress': False}}}

lsp: 2020-11-30 23:14:13 UTC pid: 3496 - MainThread - DEBUG - robocorp_ls_core.jsonrpc.streams
Writing: {'jsonrpc': '2.0', 'id': '1', 'result': {'capabilities': {'codeActionProvider': False, 'completionProvider': {'resolveProvider': False}, 'documentFormattingProvider': True, 'documentHighlightProvider': False, 'documentRangeFormattingProvider': False, 'documentSymbolProvider': False, 'definitionProvider': True, 'executeCommandProvider': {'commands': ['robot.addPluginsDir', 'robot.resolveInterpreter']}, 'hoverProvider': False, 'referencesProvider': False, 'renameProvider': False, 'foldingRangeProvider': False, 'signatureHelpProvider': {'triggerCharacters': []}, 'textDocumentSync': {'change': 2, 'save': {'includeText': False}, 'openClose': True}, 'workspace': {'workspaceFolders': {'supported': True, 'changeNotifications': True}}, 'workspaceSymbolProvider': {'workDoneProgress': False}}}}

lsp: 2020-11-30 23:14:13 UTC pid: 3496 - MainThread - DEBUG - robocorp_ls_core.jsonrpc.streams
Read: {"jsonrpc":"2.0","id":"2","method":"shutdown","params":null}

lsp: 2020-11-30 23:14:13 UTC pid: 3496 - MainThread - DEBUG - robocorp_ls_core.jsonrpc.endpoint
Handling request from client {'jsonrpc': '2.0', 'id': '2', 'method': 'shutdown', 'params': None}

lsp: 2020-11-30 23:14:13 UTC pid: 3496 - MainThread - DEBUG - robocorp_ls_core.jsonrpc.endpoint
Got result from synchronous request handler (in 0.00s): None

lsp: 2020-11-30 23:14:13 UTC pid: 3496 - MainThread - DEBUG - robocorp_ls_core.jsonrpc.streams
Writing: {'jsonrpc': '2.0', 'id': '2', 'result': None}

````

**Comment by fabioz** [comment]
In the logs I just see the language server being started and then shutdown. Have you opened the document/requested the code-completion when you got those logs?

p.s.: Please attach files with the logs instead of copying/pasting them in the issue.

**Comment by aaltat** [comment]
That is the full log and nothing is left out. In the PyCharm logs there is an indication that it could not connect the lsp server.

**Comment by aaltat** [comment]
Here are the log files 
[server.lsp.6012.log](https://github.com/robocorp/robotframework-lsp/files/5670950/server.lsp.6012.log)
[server.lsp.6049.log](https://github.com/robocorp/robotframework-lsp/files/5670951/server.lsp.6049.log)

And there is error in PyCharm which indicates that for some reason it can not connect:
![PyCharm_LSP_error](https://user-images.githubusercontent.com/2665023/101735166-21cfbf80-3aca-11eb-8182-e00164b1d90d.png)

**Comment by aaltat** [comment]
I can see this crash in the PyCharm idea.log, when using LSP 0.6.3:
```
2020-12-10 10:12:24,194 [   9611]   INFO - rocessStreamConnectionProvider - Starting server process with commands WrappedArray(/home/tatu/apps/venv/python38-sl-rf32/bin/robotframework_ls, -vv, --log-file, /home/tatu/robotframework_ls/server.log) and workingDir /home/tatu/workspace/robotframework-playwright
2020-12-10 10:12:24,204 [   9621]   INFO - rocessStreamConnectionProvider - Server process started Process[pid=8828, exitValue="not exited"]
2020-12-10 10:12:24,520 [   9937]   WARN - pper.LanguageServerWrapperImpl - org.eclipse.lsp4j.jsonrpc.MessageIssueException: Message could not be parsed.
java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.MessageIssueException: Message could not be parsed.
    at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
    at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
    at com.github.gtache.lsp.client.languageserver.wrapper.LanguageServerWrapperImpl.getServerCapabilities(LanguageServerWrapperImpl.scala:122)
    at com.github.gtache.lsp.client.languageserver.wrapper.LanguageServerWrapperImpl.connect(LanguageServerWrapperImpl.scala:188)
    at com.github.gtache.lsp.PluginMain$.$anonfun$editorOpened$2(PluginMain.scala:145)
    at com.github.gtache.lsp.PluginMain$.$anonfun$editorOpened$2$adapted(PluginMain.scala:141)
    at scala.Option.foreach(Option.scala:257)
    at com.github.gtache.lsp.PluginMain$.$anonfun$editorOpened$1(PluginMain.scala:141)
    at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
    at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
    at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:270)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
    at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.eclipse.lsp4j.jsonrpc.MessageIssueException: Message could not be parsed.
    at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponseIssues(RemoteEndpoint.java:358)
    at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handle(RemoteEndpoint.java:317)
    at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:198)
    at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
    at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    ... 1 more
2020-12-10 10:12:24,530 [   9947]   WARN - pper.LanguageServerWrapperImpl - Capabilities are null for exe : path /home/tatu/apps/venv/python38-sl-rf32/bin/robotframework_ls args : -vv --log-file /home/tatu/robotframework_ls/server.log
```
Full log 
[idea.log](https://github.com/robocorp/robotframework-lsp/files/5671226/idea.log)


When using LSP 0.5.0, there is crash but plugin is working from the PyCharm UI 
[idea_lsp_0_5_0.log](https://github.com/robocorp/robotframework-lsp/files/5671261/idea_lsp_0_5_0.log)

**Comment by fabioz** [comment]
We now have a plugin setup for the language server integration for Intellij.

See: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-intellij/README.md

**Comment by aaltat** [comment]
Thank you for great work.
