### ISSUE TITLE
There is stack trace with PyCharm LSP plugin

### ISSUE THREAD

**Issue by aaltat** [robocorp/robotframework-lsp#255]
**Describe the bug**
When I have [Browser](https://github.com/MarketSquare/robotframework-browser) library project open and I have one of the test files opened, I see this exception in the PyCharm:
```
java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: Stream closed
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
	at robocorp.lsp.intellij.InternalConnection.start(LanguageServerCommunication.java:170)
	at robocorp.lsp.intellij.LanguageServerCommunication.startInternalConnection(LanguageServerCommunication.java:346)
	at robocorp.lsp.intellij.LanguageServerCommunication.<init>(LanguageServerCommunication.java:332)
	at robocorp.lsp.intellij.LanguageServerManager.start(LanguageServerManager.java:73)
	at robocorp.lsp.intellij.LanguageServerEditorListener.editorCreated(LanguageServerEditorListener.java:53)
	at robocorp.lsp.intellij.LanguageServerEditorListener.editorCreated(LanguageServerEditorListener.java:20)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.lambda$createEditor$0(EditorFactoryImpl.java:203)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.forEachExtensionSafe(ExtensionProcessingHelper.java:33)
	at com.intellij.openapi.extensions.ExtensionPointName.forEachExtensionSafe(ExtensionPointName.java:49)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.createEditor(EditorFactoryImpl.java:203)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.createEditor(EditorFactoryImpl.java:157)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorComponent.createEditor(TextEditorComponent.java:133)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorComponent.<init>(TextEditorComponent.java:79)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl$PsiAwareTextEditorComponent.<init>(PsiAwareTextEditorImpl.java:107)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl.createEditorComponent(PsiAwareTextEditorImpl.java:85)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorImpl.<init>(TextEditorImpl.java:52)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl.<init>(PsiAwareTextEditorImpl.java:36)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorProvider.createEditor(PsiAwareTextEditorProvider.java:31)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4Edt(FileEditorManagerImpl.java:891)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl4$17(FileEditorManagerImpl.java:860)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.runBulkTabChange(FileEditorManagerImpl.java:1680)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl4$18(FileEditorManagerImpl.java:859)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:216)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:24)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeAndWait$8(ApplicationImpl.java:476)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:126)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:85)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:134)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:190)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:501)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: Stream closed
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:72)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.request(RemoteEndpoint.java:161)
	at org.eclipse.lsp4j.jsonrpc.services.EndpointProxy.invoke(EndpointProxy.java:91)
	at com.sun.proxy.$Proxy94.initialize(Unknown Source)
	at robocorp.lsp.intellij.InternalConnection.start(LanguageServerCommunication.java:166)
	... 51 more
Caused by: java.io.IOException: Stream closed
	at java.base/java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:442)
	at java.base/java.io.OutputStream.write(OutputStream.java:157)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:69)
	... 55 more
```
The error happens at the startup of the PyCharm. I am not sure what causes the error. 

There is `robotframework_ls_critical.log` file created and it contains this:
```
Traceback (most recent call last):
  File "/home/tatu/.local/share/JetBrains/PyCharmCE2020.3/robotframework-intellij/lib/robotframework_ls/__main__.py", line 134, in <module>
    main()
  File "/home/tatu/.local/share/JetBrains/PyCharmCE2020.3/robotframework-intellij/lib/robotframework_ls/__main__.py", line 87, in main
    from robotframework_ls.options import Setup, Options
  File "/home/tatu/.local/share/JetBrains/PyCharmCE2020.3/robotframework-intellij/lib/robotframework_ls/options.py", line 1, in <module>
    from robocorp_ls_core.options import *  # @UnusedWildImport (backward compatibility)
  File "/home/tatu/.local/share/JetBrains/PyCharmCE2020.3/robotframework-intellij/lib/robotframework_ls/vendored/robocorp_ls_core/options.py", line 36
    tcp: bool = False
       ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/home/tatu/.local/share/JetBrains/PyCharmCE2020.3/robotframework-intellij/lib/robotframework_ls/__main__.py", line 134, in <module>
    main()
  File "/home/tatu/.local/share/JetBrains/PyCharmCE2020.3/robotframework-intellij/lib/robotframework_ls/__main__.py", line 87, in main
    from robotframework_ls.options import Setup, Options
  File "/home/tatu/.local/share/JetBrains/PyCharmCE2020.3/robotframework-intellij/lib/robotframework_ls/options.py", line 1, in <module>
    from robocorp_ls_core.options import *  # @UnusedWildImport (backward compatibility)
  File "/home/tatu/.local/share/JetBrains/PyCharmCE2020.3/robotframework-intellij/lib/robotframework_ls/vendored/robocorp_ls_core/options.py", line 36
    tcp: bool = False
       ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/home/tatu/.local/share/JetBrains/PyCharmCE2020.3/robotframework-intellij/lib/robotframework_ls/__main__.py", line 134, in <module>
    main()
  File "/home/tatu/.local/share/JetBrains/PyCharmCE2020.3/robotframework-intellij/lib/robotframework_ls/__main__.py", line 87, in main
    from robotframework_ls.options import Setup, Options
  File "/home/tatu/.local/share/JetBrains/PyCharmCE2020.3/robotframework-intellij/lib/robotframework_ls/options.py", line 1, in <module>
    from robocorp_ls_core.options import *  # @UnusedWildImport (backward compatibility)
  File "/home/tatu/.local/share/JetBrains/PyCharmCE2020.3/robotframework-intellij/lib/robotframework_ls/vendored/robocorp_ls_core/options.py", line 36
    tcp: bool = False
       ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/home/tatu/.local/share/JetBrains/PyCharmCE2020.3/robotframework-intellij/lib/robotframework_ls/__main__.py", line 134, in <module>
    main()
  File "/home/tatu/.local/share/JetBrains/PyCharmCE2020.3/robotframework-intellij/lib/robotframework_ls/__main__.py", line 87, in main
    from robotframework_ls.options import Setup, Options
  File "/home/tatu/.local/share/JetBrains/PyCharmCE2020.3/robotframework-intellij/lib/robotframework_ls/options.py", line 1, in <module>
    from robocorp_ls_core.options import *  # @UnusedWildImport (backward compatibility)
  File "/home/tatu/.local/share/JetBrains/PyCharmCE2020.3/robotframework-intellij/lib/robotframework_ls/vendored/robocorp_ls_core/options.py", line 36
    tcp: bool = False
       ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/home/tatu/.local/share/JetBrains/PyCharmCE2020.3/robotframework-intellij/lib/robotframework_ls/__main__.py", line 134, in <module>
    main()
  File "/home/tatu/.local/share/JetBrains/PyCharmCE2020.3/robotframework-intellij/lib/robotframework_ls/__main__.py", line 87, in main
    from robotframework_ls.options import Setup, Options
  File "/home/tatu/.local/share/JetBrains/PyCharmCE2020.3/robotframework-intellij/lib/robotframework_ls/options.py", line 1, in <module>
    from robocorp_ls_core.options import *  # @UnusedWildImport (backward compatibility)
  File "/home/tatu/.local/share/JetBrains/PyCharmCE2020.3/robotframework-intellij/lib/robotframework_ls/vendored/robocorp_ls_core/options.py", line 36
    tcp: bool = False
       ^
SyntaxError: invalid syntax
```
The above error meakes me think that plugin is calling `python` somewhere, which in Ubuntu defaults to Python 2. 

**Versions:**
 - OS: Ubuntu 20.04
 - Robot Framework Version 3.2.2
 - Robot Framework Language Server Version 0.9.0
 - Client Version PyCharm 2020.3

**Comment by aaltat** [comment]
Did more debugging. If I add `python3` to Languea Server Python setting field, the `robotframework_ls_critical.log` is not anymore created. But I still get the execption in below. Also I added ` ["-vv", "--log-file=~/robotframework_ls.log"]` to Languege Server Args, but log files are not created to the user home directory. 
```
java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: Stream closed
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
	at robocorp.lsp.intellij.InternalConnection.start(LanguageServerCommunication.java:170)
	at robocorp.lsp.intellij.LanguageServerCommunication.startInternalConnection(LanguageServerCommunication.java:346)
	at robocorp.lsp.intellij.LanguageServerCommunication.<init>(LanguageServerCommunication.java:332)
	at robocorp.lsp.intellij.LanguageServerManager.start(LanguageServerManager.java:73)
	at robocorp.lsp.intellij.LanguageServerEditorListener.editorCreated(LanguageServerEditorListener.java:53)
	at robocorp.lsp.intellij.LanguageServerEditorListener.editorCreated(LanguageServerEditorListener.java:20)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.lambda$createEditor$0(EditorFactoryImpl.java:203)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.forEachExtensionSafe(ExtensionProcessingHelper.java:33)
	at com.intellij.openapi.extensions.ExtensionPointName.forEachExtensionSafe(ExtensionPointName.java:49)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.createEditor(EditorFactoryImpl.java:203)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.createEditor(EditorFactoryImpl.java:157)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorComponent.createEditor(TextEditorComponent.java:133)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorComponent.<init>(TextEditorComponent.java:79)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl$PsiAwareTextEditorComponent.<init>(PsiAwareTextEditorImpl.java:107)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl.createEditorComponent(PsiAwareTextEditorImpl.java:85)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorImpl.<init>(TextEditorImpl.java:52)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl.<init>(PsiAwareTextEditorImpl.java:36)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorProvider.createEditor(PsiAwareTextEditorProvider.java:31)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4Edt(FileEditorManagerImpl.java:891)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl4$17(FileEditorManagerImpl.java:860)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.runBulkTabChange(FileEditorManagerImpl.java:1680)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl4$18(FileEditorManagerImpl.java:859)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:216)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:24)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeAndWait$8(ApplicationImpl.java:476)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:126)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:85)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:134)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:190)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:501)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: Stream closed
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:72)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.request(RemoteEndpoint.java:161)
	at org.eclipse.lsp4j.jsonrpc.services.EndpointProxy.invoke(EndpointProxy.java:91)
	at com.sun.proxy.$Proxy94.initialize(Unknown Source)
	at robocorp.lsp.intellij.InternalConnection.start(LanguageServerCommunication.java:166)
	... 51 more
Caused by: java.io.IOException: Stream closed
	at java.base/java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:442)
	at java.base/java.io.OutputStream.write(OutputStream.java:157)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:69)
	... 55 more
```

**Comment by fabioz** [comment]
I'm releasing 0.9.1 which should hopefully give better error messages here, so, I'm closing this issue (as the stack trace isn't really helpful).

If you can still reproduce with 0.9.1, please report with an updated stack trace... 

The plugin in the Intellij Marketplace can take some time to appear updated, but you can get it manually from: https://plugins.jetbrains.com/plugin/16086-robot-framework-language-server/versions/stable/113369
