### ISSUE TITLE
Make setting to specify the language server executable project-dependent

### ISSUE THREAD

**Issue by aaltat** [robocorp/robotframework-lsp#267]
When I start PyCharm project with only project specific settings defined, I see this error:
```
java.io.IOException: Language server process exited.
Command line: [/usr/bin/python, -u, /home/tatu/.local/share/JetBrains/PyCharmCE2020.3/robotframework-intellij/lib/robotframework_ls/__main__.py].
Stderr may be seen at:
/home/tatu/.robotframework-ls/.intellij-rf-ls-2021-03-20 20_04.log
Contents (last 10000 chars):
Traceback (most recent call last):
  File "/home/tatu/.local/share/JetBrains/PyCharmCE2020.3/robotframework-intellij/lib/robotframework_ls/__main__.py", line 137, in <module>
    + sys.executable
AssertionError: Python 3+ is required for the RobotFramework Language Server.
Current executable: /usr/bin/python
Traceback (most recent call last):
  File "/home/tatu/.local/share/JetBrains/PyCharmCE2020.3/robotframework-intellij/lib/robotframework_ls/__main__.py", line 137, in <module>
    + sys.executable
AssertionError: Python 3+ is required for the RobotFramework Language Server.
Current executable: /usr/bin/python
Traceback (most recent call last):
  File "/home/tatu/.local/share/JetBrains/PyCharmCE2020.3/robotframework-intellij/lib/robotframework_ls/__main__.py", line 137, in <module>
    + sys.executable
AssertionError: Python 3+ is required for the RobotFramework Language Server.
Current executable: /usr/bin/python

	at robocorp.lsp.intellij.LanguageServerDefinition$LanguageServerStreams.verifyProcess(LanguageServerDefinition.java:144)
	at robocorp.lsp.intellij.InternalConnection.start(LanguageServerCommunication.java:176)
	at robocorp.lsp.intellij.LanguageServerCommunication.startInternalConnection(LanguageServerCommunication.java:352)
	at robocorp.lsp.intellij.LanguageServerCommunication.<init>(LanguageServerCommunication.java:338)
	at robocorp.lsp.intellij.LanguageServerManager.getLanguageServerCommunication(LanguageServerManager.java:174)
	at robocorp.lsp.intellij.FeatureSymbols$WorkspaceSymbolProvider.workspaceSymbols(FeatureSymbols.java:144)
	at robocorp.lsp.intellij.FeatureSymbols.processNames(FeatureSymbols.java:209)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel.processContributorNames(ContributorsBasedGotoByModel.java:119)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$1.processInReadAction(ContributorsBasedGotoByModel.java:86)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$1.processInReadAction(ContributorsBasedGotoByModel.java:80)
	at com.intellij.openapi.application.ReadActionProcessor.lambda$process$0(ReadActionProcessor.java:25)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:885)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.openapi.application.ReadActionProcessor.process(ReadActionProcessor.java:25)
	at com.intellij.concurrency.JobLauncherImpl.lambda$invokeConcurrentlyUnderProgress$0(JobLauncherImpl.java:50)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.concurrency.JobLauncherImpl.lambda$invokeConcurrentlyUnderProgress$1(JobLauncherImpl.java:50)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1137)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:86)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

I have this in project specific settins 
![image](https://user-images.githubusercontent.com/2665023/111881839-20603e00-89bb-11eb-8c58-74ce792bc280.png)

and this on global settings 
![image](https://user-images.githubusercontent.com/2665023/111881860-37069500-89bb-11eb-9821-4a89e899fdbb.png) then based on the error message, it looks like project specific settings are not applied.

**Comment by fabioz** [comment]
Hi @aaltat, I think I need to work a bit on a manual ;)

The issue is that you have 2 configurations:

In the global settings you must specify the python executable that's going to be used by the language server itself (this particular setting is only available at the global settings cannot be persisted in the project).

All other settings can be set to be project-specific (I'm actually working on making this setting project-specific too).

The confusion is that the configurations accept 2 settings, one for the python used to start the language server and another which can be changed which can be set per-project (so, for instance you could start the language server itself with any Python executable and then use a different target Python executable for each project -- say you have one project which requires RF 3 and another which requires RF 4, as this is the Python executable which will be used to collect RF-related information such as libraries being used).

I do need to work on the documentation (or maybe get someone to help there) so that such things are better explained.

As a note, I'm actually working on making the configurations that start the language server itself project-specific for Intellij (so, I'm going to rename this issue to that as I still hadn't created an issue for it).

**Comment by aaltat** [comment]
I am happy with both ways, but I do agree that docs are somewhat confusing. I would assume that allowing same configurations to in both (global and project) would be best solution.

**Comment by fabioz** [comment]
> I am happy with both ways, but I do agree that docs are somewhat confusing. I would assume that allowing same configurations to in both (global and project) would be best solution.

Working on it ;)
