### ISSUE TITLE
Plugin 'Robot Framework Language Server' (version '0.12.0') is not compatible with the latest version of Pycharm

### ISSUE THREAD

**Issue by zastress** [robocorp/robotframework-lsp#296]
**Describe the bug**
Pycharm plugin for RF is not compatible with latest version

**To Reproduce**
1. Install latest version of Pycharm: 
PyCharm 2021.1 (Community Edition)
Build #PC-211.6693.115, built on April 6, 2021
Runtime version: 11.0.10+9-b1341.35 amd64

2. RF plugin is disabled with this message: `Plugin error: Plugin 'Robot Framework Language Server' (version '0.12.0') is not compatible with the current version of the IDE, because it requires build 203.* or older but the current build is PC-211.6693.115`

**Comment by fabioz** [comment]
My bad... it does require build 2020.3, but I thought that it'd automatically accept newer versions too (but that doesn't seem to be the case).

I've explicitly marked the `untilBuild` in https://github.com/robocorp/robotframework-lsp/commit/992a4bb4dcf1256da3c138c00d9761b10eac318b and just created a new release with it.

It's still not in the channel because it takes some time for Intellij to approve it, but you may already install it from: https://plugins.jetbrains.com/plugin/16086-robot-framework-language-server/versions/stable/116218

**Comment by zastress** [comment]
This does not seem to work either
![2021-04-08_18-03-15](https://user-images.githubusercontent.com/37159441/114050283-cdc8c200-9894-11eb-83e4-64bc7fec6a74.png)

**Comment by fabioz** [comment]
Sorry about that. I did a respin fixing it. You can get it from: https://plugins.jetbrains.com/plugin/16086-robot-framework-language-server/versions/stable/116256 now.

**Comment by zastress** [comment]
Thanks for the fix. Now the installation was successful but I get different errors at startup:
`java.lang.RuntimeException: Unable to discover __main__.py location.
Resource file: C:\Users\Liviu\AppData\Roaming\JetBrains\PyCharmCE2021.1\plugins\robotframework-intellij-0.13.1.jar!\robotframework-intellij-resource.txt
Details:
Directory: C:\Users\Liviu\AppData\Roaming\JetBrains\PyCharmCE2021.1\plugins\robotframework-intellij-0.13.1. does not exist.
CheckedC:\Users\Liviu\AppData\Roaming\JetBrains\PyCharmCE2021.1\plugins\robotframework_ls\__main__.py
Checked:C:\Users\Liviu\AppData\Roaming\JetBrains\PyCharmCE2021.1\plugins\robotframework-ls\src\robotframework_ls\__main__.py
CheckedC:\Users\Liviu\AppData\Roaming\JetBrains\PyCharmCE2021.1\robotframework_ls\__main__.py
Checked:C:\Users\Liviu\AppData\Roaming\JetBrains\PyCharmCE2021.1\robotframework-ls\src\robotframework_ls\__main__.py
CheckedC:\Users\Liviu\AppData\Roaming\JetBrains\robotframework_ls\__main__.py
Checked:C:\Users\Liviu\AppData\Roaming\JetBrains\robotframework-ls\src\robotframework_ls\__main__.py
CheckedC:\Users\Liviu\AppData\Roaming\robotframework_ls\__main__.py
Checked:C:\Users\Liviu\AppData\Roaming\robotframework-ls\src\robotframework_ls\__main__.py
CheckedC:\Users\Liviu\AppData\robotframework_ls\__main__.py
Checked:C:\Users\Liviu\AppData\robotframework-ls\src\robotframework_ls\__main__.py
CheckedC:\Users\Liviu\robotframework_ls\__main__.py
Checked:C:\Users\Liviu\robotframework-ls\src\robotframework_ls\__main__.py
CheckedC:\Users\robotframework_ls\__main__.py
Checked:C:\Users\robotframework-ls\src\robotframework_ls\__main__.py
CheckedC:\robotframework_ls\__main__.py
Checked:C:\robotframework-ls\src\robotframework_ls\__main__.py

	at robocorp.robot.intellij.RobotFrameworkLanguage.getMain(RobotFrameworkLanguage.java:435)
	at robocorp.robot.intellij.RobotFrameworkLanguage.createProcessBuilderFromPreferences(RobotFrameworkLanguage.java:97)
	at robocorp.robot.intellij.RobotFrameworkLanguage.createLanguageServerDefinition(RobotFrameworkLanguage.java:477)
	at robocorp.robot.intellij.RobotFrameworkLanguage.getLanguageDefinition(RobotFrameworkLanguage.java:462)
	at robocorp.lsp.intellij.EditorUtils.getLanguageDefinition(EditorUtils.java:135)
	at robocorp.lsp.intellij.FeatureDefinition.resolve(FeatureDefinition.java:47)
	at robocorp.lsp.psi.LSPPsiAstElement$LSPReference.resolve(LSPPsiAstElement.java:35)
	at com.intellij.codeInsight.TargetElementUtilBase.getReferencedElement(TargetElementUtilBase.java:177)
	at com.intellij.codeInsight.TargetElementUtilBase.doGetReferenceOrReferencedElement(TargetElementUtilBase.java:165)
	at com.intellij.codeInsight.TargetElementUtilBase.getReferenceOrReferencedElement(TargetElementUtilBase.java:204)
	at com.intellij.codeInsight.TargetElementUtilBase.getReferencedElement(TargetElementUtilBase.java:248)
	at com.intellij.codeInsight.TargetElementUtilBase.doFindTargetElement(TargetElementUtilBase.java:227)
	at com.intellij.codeInsight.TargetElementUtilBase.findTargetElement(TargetElementUtilBase.java:295)
	at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:147)
	at com.intellij.model.psi.impl.TargetsKt.fromTargetEvaluator(targets.kt:177)
	at com.intellij.model.psi.impl.TargetsKt.declarationsOrReferences(targets.kt:138)
	at com.intellij.model.psi.impl.TargetsKt.declaredReferencedData(targets.kt:43)
	at com.intellij.model.psi.impl.TargetsKt.targetSymbols(targets.kt:24)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.getTargetSymbols(IdentifierHighlighterPass.java:180)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.highlightReferencesAndDeclarations(IdentifierHighlighterPass.java:172)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:92)
	at com.intellij.codeInsight.highlighting.BackgroundHighlighter.lambda$updateHighlighted$1(BackgroundHighlighter.java:147)
	at com.intellij.codeInsight.highlighting.BackgroundHighlightingUtil.lambda$lookForInjectedFileInOtherThread$0(BackgroundHighlightingUtil.java:55)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:521)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:468)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:79)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:157)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:119)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:116)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:79)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:486)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:408)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by fabioz** [comment]
This is odd... I can't really reproduce it. How have you installed it?

What contents do you have under `C:\Users\Liviu\AppData\Roaming\JetBrains\PyCharmCE2021.1\plugins\`?

**Comment by zastress** [comment]
My bad this time. Did not know I was supposed to copy the whole directory into that folder. Works now. Thank you! :)
