### ISSUE TITLE
Error showing library keyword documentation

### ISSUE THREAD

**Issue by HaaiHenkie** [robocorp/robotframework-lsp#340]
**Describe the bug**
When hovering over a keyword and pressing Ctrl+Q I receive the error: "Cannot fetch remote documentation: internal error"

**To Reproduce**
1. Open file with contents
```RobotFramework
*** Settings ***
Library     DateTime

*** Keywords ***
Today
    ${_today}=    Get Current Date    result_format=%Y-%m-%d
```
2. I put the cursor somewhere in keyword `Get Current Date`
3. I hover the mouse over keyword `Get Current Date`
4. Press Ctrl+Q

**Expected behavior**
A window with a concise description of the keyword

**Screenshots**
![image](https://user-images.githubusercontent.com/8525411/116812389-d38d8c80-ab4e-11eb-8721-33bd25344bb6.png)

**Versions:**
 - OS: Windows 10
 - Robot Framework Version 4.0.1
 - Robot Framework Language Server Version 0.14.0
 - Client Version PyCharm 2021.1.1 (bug could be reproduced in Intellij 2020.2.4

**Logs**
(renamed *.api to *.log)
[robotframework_ls.log.lint.lsp.24892.log](https://github.com/robocorp/robotframework-lsp/files/6411290/robotframework_ls.log.lint.lsp.24892.log)
[robotframework_ls.lsp.6972.log](https://github.com/robocorp/robotframework-lsp/files/6411291/robotframework_ls.lsp.6972.log)
[robotframework_ls.log.1.others.lsp.30528.log](https://github.com/robocorp/robotframework-lsp/files/6411292/robotframework_ls.log.1.others.lsp.30528.log)
[robotframework_ls.log.2.lsp.29264.log](https://github.com/robocorp/robotframework-lsp/files/6411293/robotframework_ls.log.2.lsp.29264.log)

**Comment by fabioz** [comment]
@HaaiHenkie thanks for the report... I tried but couldn't reproduce the issue and the logs don't really show anything wrong...

This hints as the issue being something in the Intellij side. In this case, can you also provide the Intellij logs?

You can find `idea.log` using `Help > Show log in explorer`.

**Comment by HaaiHenkie** [comment]
Hi @fabioz, Thanks for your quick reply

Here is the [idea.log](https://github.com/robocorp/robotframework-lsp/files/6411532/idea.log)

I tried a few more things. If I make a user keyword with documentation. the documentation will show when hovering over that keyword.

I disabled plugin 'Robot Framework Language Server' and enabled plugin 'Intellibot'. With Intellibot the library keyword documentation shows when hovering over it.

![image](https://user-images.githubusercontent.com/8525411/116816916-481ef600-ab64-11eb-9756-4f9a465cb107.png)

I also checked the 'Robot Framework Language Server' configuration. I have just one single instance of Python 3.7 installed and use it for the language server as well as interpreter for my PyCharm projects. It is my understanding that in this case I do not have to configure any python executables. Correct?

**Comment by fabioz** [comment]
The problem seems to be in some issue related to PyCharm, so, I think it'd only happen when you are hovering over keywords that map to Python files, not really robot files (I don't really have PyCharm installed, only plain Intellij, which is probably the reason I couldn't reproduce it here).

Your configuration seems to be correct.

I'll try to install PyCharm to see if I can fix it on my side.

i.e.: the error log shows:

```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'name' of com/jetbrains/python/psi/impl/PyFileImpl.multiResolveName must not be null
	at com.jetbrains.python.psi.impl.PyFileImpl.$$$reportNull$$$0(PyFileImpl.java)
	at com.jetbrains.python.psi.impl.PyFileImpl.multiResolveName(PyFileImpl.java)
	at com.jetbrains.python.psi.resolve.QualifiedNameFinder.doFindCanonicalImportPath(QualifiedNameFinder.java:146)
	at com.jetbrains.python.psi.PyUtil.getNullableParameterizedCachedValue(PyUtil.java:673)
	at com.jetbrains.python.psi.resolve.QualifiedNameFinder.findCanonicalImportPath(QualifiedNameFinder.java:111)
	at com.jetbrains.python.documentation.PythonDocumentationProvider.getOnlyUrlFor(PythonDocumentationProvider.java:642)
	at com.jetbrains.python.documentation.PythonDocumentationProvider.getUrlFor(PythonDocumentationProvider.java:510)
	at com.intellij.lang.documentation.CompositeDocumentationProvider.getUrlFor(CompositeDocumentationProvider.java:127)
	at com.intellij.codeInsight.documentation.DocumentationManager$MyCollector.lambda$getDocumentation$1(DocumentationManager.java:1559)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:521)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:468)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:79)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:157)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:119)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:116)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:79)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:486)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.executeSynchronously(NonBlockingReadActionImpl.java:422)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl.executeSynchronously(NonBlockingReadActionImpl.java:186)
	at com.intellij.codeInsight.documentation.DocumentationManager$MyCollector.getDocumentation(DocumentationManager.java:1561)
	at com.intellij.codeInsight.documentation.DocumentationManager.lambda$doFetchDocInfo$20(DocumentationManager.java:1080)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:369)
	at com.intellij.util.Alarm$Request.run(Alarm.java:355)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:220)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by HaaiHenkie** [comment]
Hi @fabioz ,

I get exactly the same error in Intellij IDEA 2021.1.1 (Community Edition) with the Python Community Edition plugin (211.7142.45). I get the error when hovering over the keyword and when pressing Ctrl+K (both calling the Quick documentation). Here are the errors I isolated from the idea.log:

[ctrl-q-error.log](https://github.com/robocorp/robotframework-lsp/files/6421028/ctrl-q-error.log)
[hoover-error.log](https://github.com/robocorp/robotframework-lsp/files/6421029/hoover-error.log)

So I do not think it is related to PyCharm. I have no idea how this API works, but I guess the quick documentation is looked up with the name of the keyword. Are you sure this information is passed on correctly in case of hovering and pressing ctrl+q? Because something does not seem to get resolved properly.

Cheers,

Henk

**Comment by fabioz** [comment]
@HaaiHenkie yes, I'm sure it's related to PyCharm (which is the same as Intellij + Python plugin)... as you can see in the stack trace attached, all the error trace comes from `com.jetbrains.python`, whereas the language server is in a completely different workspace (which doesn't even appear there).

What I think is happening is that because the language server creates a reference to a Python file then the Python plugin tries to take over to improve the info and fails in the middle of it -- I still haven't been able to debug it properly on why it does that (possibly the reference that is created doesn't please the Python plugin as it expects) as I'm finishing something else, but this is high on my priority list and I plan on tackle that before the next release.

**Comment by HaaiHenkie** [comment]
Updated to version 0.15 and it works. Thanks!
