### ISSUE TITLE
[vscode] "Error processing message: _debug_adapter_pydevd_target_comm" when launching from launch config

### ISSUE THREAD

**Issue by DetachHead** [robocorp/robotframework-lsp#433]
**Screenshots**
![image](https://user-images.githubusercontent.com/57028336/131068710-10717445-9e95-45b5-b4bf-f07dc5d4bc67.png)

**Versions:**
 - OS: windows 10
 - Robot Framework Version: 4.1
 - Robot Framework Language Server Version: 0.21.0
 - Client Version: vscode 1.59.1

**Comment by DetachHead** [comment]
```
dap: 2021-09-02 09:33:32 UTC pid: 22728 - Read from client (dap __main__) - EXCEPTION - robocorp_ls_core.debug_adapter_core.debug_adapter_threads
Error processing message.

Traceback (most recent call last):
  File "c:\Users\user\.vscode\extensions\robocorp.robotframework-lsp-0.21.0\src\robotframework_ls\vendored\robocorp_ls_core\debug_adapter_core\debug_adapter_threads.py", line 143, in reader_thread
    process_command(protocol_message)
  File "c:\Users\user\.vscode\extensions\robocorp.robotframework-lsp-0.21.0\src\robotframework_debug_adapter\debug_adapter_comm.py", line 113, in from_client
    on_request(protocol_message)
  File "c:\Users\user\.vscode\extensions\robocorp.robotframework-lsp-0.21.0\src\robotframework_debug_adapter\debug_adapter_comm.py", line 184, in on_launch_request
    launch_process.write_to_pydevd(
  File "c:\Users\user\.vscode\extensions\robocorp.robotframework-lsp-0.21.0\src\robotframework_debug_adapter\launch_process.py", line 354, in write_to_pydevd
    self._debug_adapter_pydevd_target_comm.write_to_pydevd_message(
AttributeError: _debug_adapter_pydevd_target_comm
```

**Comment by hbirkdale** [comment]
Getting the same message
