### ISSUE TITLE
Environment variables for Library libspec not populated

### ISSUE THREAD

**Issue by DanielPenning** [robocorp/robotframework-lsp#535]
**Describe the bug**
When using environment variables within the Library setting, RobotFramework LS does not populate them for linting.
This means Auto Completion is not available for this library.

**To Reproduce**
```
*** Settings ***
Library    Remote    http://%{MYREMOTELIB}:8270

*** Test Cases ***
Log Variable
    Log To Console    %{MYREMOTELIB}
```

The environment variable MYREMOTELIB is set. It is displayed correctly by `Log To Console`.
However the Libspec generation fails. The log (attached below) shows that the %{...} part is not replaced by the value of the environment variable. Robotframework itself parses this line correctly so it connects to the remote library sucessfully.

**Expected behavior**
Environment variables should also be populated for the Libspec generation within RobotFramwork LS.

**Versions:**
 - OS Windows 10
 - Robot Framework 4.1.3
 - Robot Framework Language Server Version: v0.35.0
 - Client Version: VS Code 1.63.2

**Logs**
`Traceback (most recent call last):
  File "c:\Users\User\.vscode\extensions\robocorp.robotframework-lsp-0.35.0\src\robotframework_ls\impl\libspec_manager.py", line 893, in _cached_create_libspec
    self._subprocess_check_output(
  File "c:\Users\User\.vscode\extensions\robocorp.robotframework-lsp-0.35.0\src\robotframework_ls\impl\libspec_manager.py", line 788, in _subprocess_check_output
    return subprocess.check_output(*args, **kwargs)
  File "C:\Python\Python310\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Python\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['c:\\venv-3.10\\Scripts\\python.exe', '-m', 'robot.libdoc', 'Remote::http://%{MYREMOTELIB}:8270', 'C:\\Users\\User\\.robotframework-ls\\specs\\v2\\c5bf7942_4.1.3\\user\\Remote82be87aa.libspec']' returned non-zero exit status 252.`

**Comment by DanielPenning** [comment]
I can confirm this is working as desired in v0.38.1. Thanks a lot!
