### ISSUE TITLE
Debugger is crashed with proper error message

### ISSUE THREAD

**Issue by nikiost** [robocorp/robotframework-lsp#556]
**Describe the bug**
Debugger is crashed with proper error message

**To Reproduce**
1. define 'run configuration'
2. put breakpoint in desire area
3. run debugger

**Expected behavior**
Debugging will stop on breakpoint

**Screenshots**
N/A

**Versions:**
PyCharm 2021.3.1 (Community Edition)
Build #PC-213.6461.77, built on December 28, 2021
Runtime version: 11.0.13+7-b1751.21 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2020M
Cores: 8
Non-Bundled Plugins:
    robocorp.lsp.intellij (0.38.1)
    com.godwin.json.parser (1.4.1)

**Logs**
com.intellij.execution.ExecutionException
	at robocorp.dap.RobotProgramRunner$1.start(RobotProgramRunner.java:77)
	at com.intellij.xdebugger.impl.XDebuggerManagerImpl.startSession(XDebuggerManagerImpl.java:273)
	at com.intellij.xdebugger.impl.XDebuggerManagerImpl.startSession(XDebuggerManagerImpl.java:234)
	at robocorp.dap.RobotProgramRunner.lambda$execute$0(RobotProgramRunner.java:70)
	at com.intellij.execution.impl.ExecutionManagerImpl$startRunProfile$1.invoke(ExecutionManagerImpl.kt:173)
	at com.intellij.execution.impl.ExecutionManagerImpl$startRunProfile$1.invoke(ExecutionManagerImpl.kt:72)
	at com.intellij.execution.impl.ExecutionManagerImpl$doStartRunProfile$startRunnable$1.run(ExecutionManagerImpl.kt:234)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:348)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:131)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:187)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1886)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021)
	at robocorp.dap.RobotDebugProcess.<init>(RobotDebugProcess.java:275)
	at robocorp.dap.RobotProgramRunner$1.start(RobotProgramRunner.java:75)
	... 35 more

**Comment by fabioz** [comment]
The stacktrace just shows that the launch didn't really complete in 15 seconds, but it doesn't really say the reason... to get that info, can you please add the following environment variables to the launch:

```
ROBOTFRAMEWORK_DAP_LOG_FILENAME=<c:/path/to/debugger.log>
ROBOTFRAMEWORK_DAP_LOG_LEVEL=3
```

(changing `<c:/path/to/debugger.log>` to a filename pointing to a file in a directory that exists in your machine) 

Then rerun and provide the `debugger.xxx.<pid>.log` files which should've been generated.

**Comment by nikiost** [comment]
Please review the debugs)

[debugger.dap.59144.log](https://github.com/robocorp/robotframework-lsp/files/7965872/debugger.dap.59144.log)
[debugger.robot.19288.log](https://github.com/robocorp/robotframework-lsp/files/7965873/debugger.robot.19288.log)

**Comment by fabioz** [comment]
Thank you for the logs.

I **think** I found the culprit but I'm not 100% sure... given that, do you think you can get a pre-release version and test it locally to see if it fixes it for you? 

Note: if it doesn't fix it, please send new logs with that version (I also did some changes to the logging and an additional file should be created with the python debugger logs).

You can get the build at:

https://github.com/robocorp/robotframework-lsp/actions/runs/1772254154

If you need instructions on how to install that version, please see: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/faq.md#how-to-install-a-build-from-github-on-intellij

**Comment by nikiost** [comment]
> Thank you for the logs.
> 
> I **think** I found the culprit but I'm not 100% sure... given that, do you think you can get a pre-release version and test it locally to see if it fixes it for you?
> 
> Note: if it doesn't fix it, please send new logs with that version (I also did some changes to the logging and an additional file should be created with the python debugger logs).
> 
> You can get the build at:
> 
> https://github.com/robocorp/robotframework-lsp/actions/runs/1772254154
> 
> If you need instructions on how to install that version, please see: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/faq.md#how-to-install-a-build-from-github-on-intellij

Sure no problem!

**Comment by nikiost** [comment]
Looks good so far)
Great job!

**Comment by fabioz** [comment]
Great, thanks for the feedback.

Closed in: https://github.com/robocorp/robotframework-lsp/commit/dc4152fdc45b8efdffe92c28c64345fb1daab5c5
