### ISSUE TITLE
IllegalArgumentException Error - Starts blocking PyCharm and turns it very slow

### ISSUE THREAD

**Issue by hcortepi** [robocorp/robotframework-lsp#565]
**Describe the bug**
While using the Robot Framework Language server with PyCharm version 2021.2.4 (Community Edition) it keeps throwing IDE Fatal Errors which causes the system to get very slow.

One of the latest errors is:
```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'textAttributes' of com/intellij/codeInsight/daemon/impl/B.textAttributes must not be null
	at com.intellij.codeInsight.daemon.impl.B.$$$reportNull$$$0(B.java)
	at com.intellij.codeInsight.daemon.impl.B.textAttributes(B.java)
	at robocorp.lsp.intellij.FeatureSemanticHighlighting.apply(FeatureSemanticHighlighting.java:136)
	at robocorp.lsp.intellij.FeatureSemanticHighlighting.apply(FeatureSemanticHighlighting.java:28)
	at com.intellij.codeInsight.daemon.impl.AnnotationHolderImpl.applyExternalAnnotatorWithContext(AnnotationHolderImpl.java:203)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doApply(ExternalToolPass.java:228)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.lambda$run$1(ExternalToolPass.java:195)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:52)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:854)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:51)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.lambda$run$2(ExternalToolPass.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:270)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:248)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:190)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:333)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:323)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:273)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:287)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:242)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:240)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:391)
	at com.intellij.util.Alarm$Request.run(Alarm.java:377)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:220)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**To Reproduce**
- The behavior started ocurring more when using the keyboard shortcut `Command` + mouse click to access the keywords declarations.

**Screenshots**
<img width="840" alt="image" src="https://user-images.githubusercontent.com/78511917/152662973-d5888990-64ba-4775-9f9c-99af90d50083.png">

**Versions:**
 - OS: macOS Monterey V12.2 (Intel Core i7)
 - Robot Framework Version: 4.1
 - Robot Framework Language Server Version: 0.39.0
 - Client Version: 2021.2.4

**Comment by cplasse** [comment]
I have the same error on IntelliJ 2021.3.2 and 0.39.0 plugin version. Downgrading to 0.38.1 works as workaround.

**Comment by fabioz** [comment]
I'm sorry about that. I've just fixed it and pushed a new release for the `Robot Framework Language Server` (`0.39.1`) on Intellij.

Please install it from: https://plugins.jetbrains.com/plugin/16086-robot-framework-language-server/versions/stable/156787 and let me know how it goes ;)

**Comment by cplasse** [comment]
Thanks for fix, it works after IntelliJ plugin update
