### ISSUE TITLE
"Error generating libspec" error when importing library with function parameter that uses new union syntax

### ISSUE THREAD

**Issue by DetachHead** [robocorp/robotframework-lsp#602]
**Describe the bug**
`test.py`:
```py
def foo(src: str | None) -> None:
    ...
```
`test.robot`:
```robot
*** Settings ***
Library     Sandpit.test
```

**To Reproduce**
1. Open `test.robot`

**Screenshots**
![image](https://user-images.githubusercontent.com/57028336/158282962-5f9c7811-7c17-4f2b-9eb1-83e1150fa347.png)

**Versions:**
 - OS: windows 10
 - Robot Framework Version: 5.0b1
 - Robot Framework Language Server Version: 0.42.1
 - Client Version: vscode 1.65.1
 - python version: 3.10

**Logs**
```
server-api: 2022-03-15 10:40:45 UTC pid: 31012 - ThreadPoolExecutor-0_1 - EXCEPTION - robotframework_ls.impl.libspec_manager
Error creating libspec: Sandpit.test.
Return code: 252
Output:
Building library 'Sandpit.test' failed: KeyError: typing.Union



Try --help for usage information.



Traceback (most recent call last):
  File "c:\Users\amogus\.vscode\extensions\robocorp.robotframework-lsp-0.42.1\src\robotframework_ls\impl\libspec_manager.py", line 960, in _cached_create_libspec
    self._subprocess_check_output(
  File "c:\Users\amogus\.vscode\extensions\robocorp.robotframework-lsp-0.42.1\src\robotframework_ls\impl\libspec_manager.py", line 842, in _subprocess_check_output
    return subprocess.check_output(*args, **kwargs)
  File "C:\Users\amogus\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\amogus\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Users\\amogus\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\project-XrR4RrAa-py3.10\\Scripts\\python.exe', '-m', 'robot.libdoc', '--format', 'XML', '--specdocformat', 'RAW', '-P', 'c:\\Users\\amogus\\project', 'Sandpit.test', 'C:\\Users\\amogus\\.robotframework-ls\\specs\\v2\\b4caba04_5.0b1\\user\\Sandpit.test.libspec']' returned non-zero exit status 252.
server-api: 2022-03-15 10:40:45 UTC pid: 31012 - ThreadPoolExecutor-0_0 - INFO - robotframework_ls.impl.libspec_manager
Library Sandpit.test is invalid. Current source to mtime:
{'c:\\users\\amogus\\project\\sandpit\\test.py': 1647304151.3413062}
Changed from:
{'c:\\users\\amogus\\project\\sandpit\\test.py': 1647304184.406856}
```

**Comment by fabioz** [comment]
If you try to build the libdoc for the library on the command line (with `python -m robot.libdoc <library_name> <library_name.libspec>`), do you have the same error?

If you do, please report this as an issue in https://github.com/robotframework/robotframework/issues.
