### ISSUE TITLE
Need to restart Vs Code for changes to be taken into account

### ISSUE THREAD

**Issue by Franz333** [robocorp/robotframework-lsp#623]
**Description**
After modifying a keyword by for example adding or removing an argument I need to restart VsCode in order for the changes to be taken into account by RobotFramework LS. Before, the changes would be "known" instantly by to linter.

For the past few weeks I have often had a pop from the extension announcing problems and inviting me to consult them in the output tab but it was not creating problems in my everyday use. Now it is really bothering me and preventing me from using the tool normally.

**Versions:**
 - OS: Windows 10 Professionnel - 21H2
 - Robot Framework Version: 4.1.3
 - Robot Framework Language Server Version: v0.42.0 
 - Python 3.7.6
 - VSCode 1.65.2

**Logs**
Here is a piece of log that I receive.. 

=============================== END Thread Dump ===============================

lsp: 2022-03-28 16:28:43 UTC pid: 21620 - MainThread - INFO - robocorp_ls_core.jsonrpc.monitor
Cancelled: Message: id: 63, method: textDocument/semanticTokens/full

lsp: 2022-03-28 16:28:43 UTC pid: 21620 - ThreadPoolExecutor-0_1 - INFO - robotframework_ls.robotframework_ls_impl
Cancelled handling: <function RobotFrameworkLanguageServer._threaded_api_request_no_doc at 0x0000022FFD5BB168>

lsp: 2022-03-28 16:28:43 UTC pid: 21620 - MainThread - INFO - robocorp_ls_core.jsonrpc.monitor
Cancelled: Message: id: 64, method: textDocument/semanticTokens/full

lsp: 2022-03-28 16:28:43 UTC pid: 21620 - ThreadPoolExecutor-0_6 - INFO - robotframework_ls.robotframework_ls_impl
Cancelled handling: <function RobotFrameworkLanguageServer._threaded_api_request_no_doc at 0x0000022FFD5BB168>

server-api: 2022-03-28 16:28:43 UTC pid: 12496 - MainThread - INFO - robocorp_ls_core.jsonrpc.monitor
Cancelled: Message: id: 66, method: textDocument/semanticTokens/full

server-api: 2022-03-28 16:28:43 UTC pid: 12496 - MainThread - INFO - robocorp_ls_core.jsonrpc.endpoint
Received cancel notification for unknown message id 67

lsp: 2022-03-28 16:32:07 UTC pid: 21620 - MainThread - INFO - robocorp_ls_core.jsonrpc.monitor
Cancelled: Message: id: 82, method: textDocument/hover

lsp: 2022-03-28 16:49:41 UTC pid: 21620 - MainThread - INFO - robocorp_ls_core.jsonrpc.monitor
Cancelled: Message: id: 98, method: textDocument/hover

lsp: 2022-03-28 16:54:38 UTC pid: 21620 - MainThread - INFO - robocorp_ls_core.jsonrpc.endpoint
Ignoring notification for unknown method $/setTrace

lsp: 2022-03-28 16:55:02 UTC pid: 21620 - MainThread - INFO - robocorp_ls_core.jsonrpc.monitor
Cancelled: Message: id: 111, method: textDocument/hover

lsp: 2022-03-28 16:55:02 UTC pid: 21620 - ThreadPoolExecutor-0_3 - INFO - robotframework_ls.robotframework_ls_impl
Cancelled handling: <function RobotFrameworkLanguageServer._threaded_api_request at 0x0000022FFD5BB048>

server-api: 2022-03-28 16:55:02 UTC pid: 21376 - MainThread - INFO - robocorp_ls_core.jsonrpc.monitor
Cancelled: Message: id: 72, method: hover

lsp: 2022-03-28 16:57:02 UTC pid: 21620 - MainThread - INFO - robocorp_ls_core.jsonrpc.monitor
Cancelled: Message: id: 195, method: textDocument/foldingRange

lsp: 2022-03-28 16:57:03 UTC pid: 21620 - MainThread - INFO - robocorp_ls_core.jsonrpc.monitor
Cancelled: Message: id: 204, method: textDocument/foldingRange

lsp: 2022-03-28 16:57:03 UTC pid: 21620 - ThreadPoolExecutor-0_4 - INFO - robotframework_ls.robotframework_ls_impl
Cancelled handling: <function RobotFrameworkLanguageServer._threaded_api_request at 0x0000022FFD5BB048>

server-api: 2022-03-28 16:57:03 UTC pid: 12496 - MainThread - INFO - robocorp_ls_core.jsonrpc.endpoint
Received cancel notification for unknown message id 178

lsp: 2022-03-28 16:57:34 UTC pid: 21620 - MainThread - INFO - robocorp_ls_core.jsonrpc.endpoint
Received cancel notification for unknown message id 298

server-api: 2022-03-28 16:59:10 UTC pid: 13832 - MainThread - INFO - robocorp_ls_core.jsonrpc.monitor
Cancelled: Message: id: 164, method: lint

lsp: 2022-03-28 16:59:11 UTC pid: 21620 - MainThread - INFO - robocorp_ls_core.jsonrpc.monitor
Cancelled: Message: id: 460, method: textDocument/hover

server-api: 2022-03-28 16:59:38 UTC pid: 12496 - ThreadPoolExecutor-0_5 - INFO - robocorp_ls_core.robotidy_wrapper
Using vendored robotidy

server-api: 2022-03-28 16:59:38 UTC pid: 12496 - ThreadPoolExecutor-0_5 - INFO - robocorp_ls_core.robotidy_wrapper
robotidy module: <module 'robotidy' from 'c:\\Users\\roberto.baggio\\.vscode\\extensions\\robocorp.robotframework-lsp-0.42.0\\src\\robotframework_ls\\vendored\\robocorp_ls_core\\libs\\robotidy_lib\\robotidy\\__init__.py'>

lsp: 2022-03-28 16:59:42 UTC pid: 21620 - MainThread - EXCEPTION - robocorp_ls_core.jsonrpc.endpoint
Failed to handle request 492

Traceback (most recent call last):
  File "c:\Users\roberto.baggio\.vscode\extensions\robocorp.robotframework-lsp-0.42.0\src\robotframework_ls\vendored\robocorp_ls_core\jsonrpc\endpoint.py", line 142, in consume
    message["id"], message["method"], message.get("params")
  File "c:\Users\roberto.baggio\.vscode\extensions\robocorp.robotframework-lsp-0.42.0\src\robotframework_ls\vendored\robocorp_ls_core\jsonrpc\endpoint.py", line 277, in _handle_request
    handler_result = handler(params)
  File "c:\Users\roberto.baggio\.vscode\extensions\robocorp.robotframework-lsp-0.42.0\src\robotframework_ls\vendored\robocorp_ls_core\jsonrpc\dispatchers.py", line 49, in _handler
    return method(**(params or {}))
  File "c:\Users\roberto.baggio\.vscode\extensions\robocorp.robotframework-lsp-0.42.0\src\robotframework_ls\robotframework_ls_impl.py", line 586, in m_text_document__formatting
    raise RuntimeError("Code formatting timed-out.")
RuntimeError: Code formatting timed-out.
[Error - 16:59:42] Request textDocument/formatting failed.
  Message: RuntimeError: Code formatting timed-out.
  Code: -32602 
[object Object]
server-api: 2022-03-28 16:59:42 UTC pid: 12496 - ThreadPoolExecutor-0_0 - INFO - robocorp_ls_core.robotidy_wrapper
robotidy module: <module 'robotidy' from 'c:\\Users\\roberto.baggio\\.vscode\\extensions\\robocorp.robotframework-lsp-0.42.0\\src\\robotframework_ls\\vendored\\robocorp_ls_core\\libs\\robotidy_lib\\robotidy\\__init__.py'>

server-api: 2022-03-28 16:59:43 UTC pid: 12496 - Thread-5 - CRITICAL - robocorp_ls_core.jsonrpc.endpoint
===============================================================================
Slow request (already took: 5s). Showing thread dump.
================================= Thread Dump =================================

-------------------------------------------------------------------------------
 Thread <Thread(ThreadPoolExecutor-0_5, started daemon 15768)>

self: <difflib.SequenceMatcher object at 0x000001E1888E8108>

 File "C:\Users\roberto.baggio\AppData\Local\Programs\Python\Python37\lib\threading.py", line 890, in _bootstrap
   self._bootstrap_inner()
 File "C:\Users\roberto.baggio\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
   self.run()
 File "C:\Users\roberto.baggio\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
   self._target(*self._args, **self._kwargs)
 File "C:\Users\roberto.baggio\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 80, in _worker
   work_item.run()
 File "C:\Users\roberto.baggio\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
   result = self.fn(*self.args, **self.kwargs)
 File "c:\Users\roberto.baggio\.vscode\extensions\robocorp.robotframework-lsp-0.42.0\src\robotframework_ls\vendored\robocorp_ls_core\jsonrpc\endpoint.py", line 263, in _call_checking_time
   return func(**kwargs)
 File "c:\Users\roberto.baggio\.vscode\extensions\robocorp.robotframework-lsp-0.42.0\src\robotframework_ls\server_api\server.py", line 581, in _threaded_code_format
   return [x.to_dict() for x in create_text_edit_from_diff(text, new_contents)]
 File "c:\Users\roberto.baggio\.vscode\extensions\robocorp.robotframework-lsp-0.42.0\src\robotframework_ls\impl\formatting.py", line 38, in create_text_edit_from_diff
   for tag, i1, i2, j1, j2 in s.get_opcodes():
 File "C:\Users\roberto.baggio\AppData\Local\Programs\Python\Python37\lib\difflib.py", line 550, in get_opcodes
   for ai, bj, size in self.get_matching_blocks():
 File "C:\Users\roberto.baggio\AppData\Local\Programs\Python\Python37\lib\difflib.py", line 479, in get_matching_blocks
   i, j, k = x = self.find_longest_match(alo, ahi, blo, bhi)
 File "C:\Users\roberto.baggio\AppData\Local\Programs\Python\Python37\lib\difflib.py", line 410, in find_longest_match
   k = newj2len[j] = j2lenget(j-1, 0) + 1

=============================== END Thread Dump ===============================

server-api: 2022-03-28 17:00:25 UTC pid: 12496 - ThreadPoolExecutor-0_3 - INFO - robocorp_ls_core.robotidy_wrapper
robotidy module: <module 'robotidy' from 'c:\\Users\\roberto.baggio\\.vscode\\extensions\\robocorp.robotframework-lsp-0.42.0\\src\\robotframework_ls\\vendored\\robocorp_ls_core\\libs\\robotidy_lib\\robotidy\\__init__.py'>

lsp: 2022-03-28 17:00:36 UTC pid: 21620 - MainThread - INFO - robocorp_ls_core.jsonrpc.monitor
Cancelled: Message: id: 546, method: textDocument/hover

lsp: 2022-03-28 17:00:36 UTC pid: 21620 - ThreadPoolExecutor-0_0 - INFO - robotframework_ls.robotframework_ls_impl
Cancelled handling: <function RobotFrameworkLanguageServer._threaded_api_request at 0x0000022FFD5BB048>

server-api: 2022-03-28 17:00:36 UTC pid: 21376 - MainThread - INFO - robocorp_ls_core.jsonrpc.monitor
Cancelled: Message: id: 316, method: hover

server-api: 2022-03-28 17:20:36 UTC pid: 12496 - ThreadPoolExecutor-0_4 - INFO - robocorp_ls_core.robotidy_wrapper
robotidy module: <module 'robotidy' from 'c:\\Users\\roberto.baggio\\.vscode\\extensions\\robocorp.robotframework-lsp-0.42.0\\src\\robotframework_ls\\vendored\\robocorp_ls_core\\libs\\robotidy_lib\\robotidy\\__init__.py'>

lsp: 2022-03-28 17:20:48 UTC pid: 21620 - MainThread - INFO - robocorp_ls_core.jsonrpc.monitor
Cancelled: Message: id: 733, method: textDocument/hover

server-api: 2022-03-28 17:22:41 UTC pid: 12496 - ThreadPoolExecutor-0_7 - INFO - robocorp_ls_core.robotidy_wrapper
robotidy module: <module 'robotidy' from 'c:\\Users\\roberto.baggio\\.vscode\\extensions\\robocorp.robotframework-lsp-0.42.0\\src\\robotframework_ls\\vendored\\robocorp_ls_core\\libs\\robotidy_lib\\robotidy\\__init__.py'>

server-api: 2022-03-28 17:22:52 UTC pid: 12496 - ThreadPoolExecutor-0_2 - INFO - robocorp_ls_core.robotidy_wrapper
robotidy module: <module 'robotidy' from 'c:\\Users\\roberto.baggio\\.vscode\\extensions\\robocorp.robotframework-lsp-0.42.0\\src\\robotframework_ls\\vendored\\robocorp_ls_core\\libs\\robotidy_lib\\robotidy\\__init__.py'>

lsp: 2022-03-28 17:22:53 UTC pid: 21620 - MainThread - INFO - robocorp_ls_core.jsonrpc.monitor
Cancelled: Message: id: 771, method: textDocument/hover

server-api: 2022-03-28 17:23:06 UTC pid: 12496 - ThreadPoolExecutor-0_6 - INFO - robocorp_ls_core.robotidy_wrapper
robotidy module: <module 'robotidy' from 'c:\\Users\\roberto.baggio\\.vscode\\extensions\\robocorp.robotframework-lsp-0.42.0\\src\\robotframework_ls\\vendored\\robocorp_ls_core\\libs\\robotidy_lib\\robotidy\\__init__.py'>

lsp: 2022-03-28 17:24:30 UTC pid: 21620 - MainThread - INFO - robocorp_ls_core.jsonrpc.endpoint
Ignoring notification for unknown method $/setTrace

lsp: 2022-03-28 17:24:33 UTC pid: 21620 - MainThread - INFO - robocorp_ls_core.jsonrpc.endpoint
Ignoring notification for unknown method $/setTrace

lsp: 2022-03-28 17:24:33 UTC pid: 21620 - MainThread - INFO - robocorp_ls_core.jsonrpc.endpoint
Ignoring notification for unknown method $/setTrace

lsp: 2022-03-28 17:34:03 UTC pid: 21620 - MainThread - INFO - robocorp_ls_core.jsonrpc.endpoint
Ignoring notification for unknown method $/setTrace

**Comment by Franz333** [comment]
Hi Fabioz,
Thank you for your answer.
I did the upgrade but it does not change anything.
I tried again with a simple example: "modify a KW that has one argument by adding a second one"
Here is the log

Getting language server Python executable.
Waiting for RobotFramework (python) Language Server to finish activating...
Starting RobotFramework Language Server with args: C:\Users\roberto.baggio\AppData\Local\Programs\Python\Python37\python.exe,-u,c:\Users\roberto.baggio\.vscode\extensions\robocorp.robotframework-lsp-0.42.0\src\robotframework_ls\__main__.py,-v
lsp: 2022-03-29 08:37:59 UTC pid: 4164 - MainThread - INFO - robotframework_ls.__main__
Arguments: ['-v']

lsp: 2022-03-29 08:37:59 UTC pid: 4164 - MainThread - INFO - robotframework_ls.__main__
Python: 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)] - lsp: 0.42.0 (<module 'robotframework_ls' from 'c:\\Users\\roberto.baggio\\.vscode\\extensions\\robocorp.robotframework-lsp-0.42.0\\src\\robotframework_ls\\__init__.py'>) - platform: win32 - sys.prefix: C:\Users\roberto.baggio\AppData\Local\Programs\Python\Python37 - sys.executable: C:\Users\roberto.baggio\AppData\Local\Programs\Python\Python37\python.exe

lsp: 2022-03-29 08:37:59 UTC pid: 4164 - MainThread - INFO - robocorp_ls_core.python_ls
Starting RobotFrameworkLanguageServer IO language server. pid: 4164

lsp: 2022-03-29 08:37:59 UTC pid: 4164 - MainThread - INFO - robotframework_ls.robotframework_ls_impl
Using watch implementation: watchdog (customize with ROBOTFRAMEWORK_LS_WATCH_IMPL environment variable)

lsp: 2022-03-29 08:37:59 UTC pid: 4164 - MainThread - INFO - robocorp_ls_core.remote_fs_observer_impl
Initializing Remote FS Observer with the following args: ['C:\\Users\\roberto.baggio\\AppData\\Local\\Programs\\Python\\Python37\\python.exe', '-u', 'c:\\Users\\roberto.baggio\\.vscode\\extensions\\robocorp.robotframework-lsp-0.42.0\\src\\robotframework_ls\\vendored\\robocorp_ls_core\\remote_fs_observer__main__.py', '-v']

remote_fs_observer: 2022-03-29 08:37:59 UTC pid: 21792 - MainThread - INFO - robocorp_ls_core.remote_fs_observer__main__

Arguments: ['-v']

remote_fs_observer: 2022-03-29 08:37:59 UTC pid: 21792 - MainThread - INFO - robocorp_ls_core.remote_fs_observer__main__

Python: 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)] - lsp: <unable to get __version__> (<module 'robocorp_ls_core' from 'c:\\Users\\roberto.baggio\\.vscode\\extensions\\robocorp.robotframework-lsp-0.42.0\\src\\robotframework_ls\\vendored\\robocorp_ls_core\\__init__.py'>) - platform: win32 - sys.prefix: C:\Users\roberto.baggio\AppData\Local\Programs\Python\Python37 - sys.executable: C:\Users\roberto.baggio\AppData\Local\Programs\Python\Python37\python.exe

server-api: 2022-03-29 08:38:01 UTC pid: 15044 - MainThread - INFO - robotframework_ls.__main__
Arguments: ['-v']

server-api: 2022-03-29 08:38:01 UTC pid: 15044 - MainThread - INFO - robotframework_ls.__main__
Python: 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)] - lsp: 0.42.0 (<module 'robotframework_ls' from 'c:\\Users\\roberto.baggio\\.vscode\\extensions\\robocorp.robotframework-lsp-0.42.0\\src\\robotframework_ls\\__init__.py'>) - platform: win32 - sys.prefix: C:\Users\roberto.baggio\AppData\Local\Programs\Python\Python37 - sys.executable: C:\Users\roberto.baggio\AppData\Local\Programs\Python\Python37\python.exe

server-api: 2022-03-29 08:38:01 UTC pid: 15044 - MainThread - INFO - robocorp_ls_core.python_ls
Starting RobotFrameworkServerApiWithObserver IO language server. pid: 15044

server-api: 2022-03-29 08:38:02 UTC pid: 15044 - MainThread - INFO - robotframework_ls.impl.libspec_manager
User libspec dir: C:\Users\roberto.baggio\.robotframework-ls\specs\v2\0c540f60_4.1.3\user

server-api: 2022-03-29 08:38:02 UTC pid: 15044 - MainThread - INFO - robotframework_ls.impl.libspec_manager
Builtins libspec dir: C:\Users\roberto.baggio\.robotframework-ls\specs\v2\0c540f60_4.1.3\builtins

server-api: 2022-03-29 08:38:02 UTC pid: 15044 - MainThread - INFO - robotframework_ls.impl.libspec_manager
Cache libspec dir: C:\Users\roberto.baggio\.robotframework-ls\specs\v2\0c540f60_4.1.3\cache

server-api: 2022-03-29 08:38:03 UTC pid: 20444 - MainThread - INFO - robotframework_ls.__main__
Arguments: ['-v']

server-api: 2022-03-29 08:38:03 UTC pid: 20444 - MainThread - INFO - robotframework_ls.__main__
Python: 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)] - lsp: 0.42.0 (<module 'robotframework_ls' from 'c:\\Users\\roberto.baggio\\.vscode\\extensions\\robocorp.robotframework-lsp-0.42.0\\src\\robotframework_ls\\__init__.py'>) - platform: win32 - sys.prefix: C:\Users\roberto.baggio\AppData\Local\Programs\Python\Python37 - sys.executable: C:\Users\roberto.baggio\AppData\Local\Programs\Python\Python37\python.exe

server-api: 2022-03-29 08:38:03 UTC pid: 20444 - MainThread - INFO - robocorp_ls_core.python_ls
Starting RobotFrameworkServerApiWithObserver IO language server. pid: 20444

server-api: 2022-03-29 08:38:04 UTC pid: 20444 - MainThread - INFO - robotframework_ls.impl.libspec_manager
User libspec dir: C:\Users\roberto.baggio\.robotframework-ls\specs\v2\0c540f60_4.1.3\user

server-api: 2022-03-29 08:38:04 UTC pid: 20444 - MainThread - INFO - robotframework_ls.impl.libspec_manager
Builtins libspec dir: C:\Users\roberto.baggio\.robotframework-ls\specs\v2\0c540f60_4.1.3\builtins

server-api: 2022-03-29 08:38:04 UTC pid: 20444 - MainThread - INFO - robotframework_ls.impl.libspec_manager
Cache libspec dir: C:\Users\roberto.baggio\.robotframework-ls\specs\v2\0c540f60_4.1.3\cache

RobotFramework Language Server ready. Took: 8.7s
server-api: 2022-03-29 08:38:04 UTC pid: 4740 - MainThread - INFO - robotframework_ls.__main__
Arguments: ['-v']

server-api: 2022-03-29 08:38:04 UTC pid: 4740 - MainThread - INFO - robotframework_ls.__main__
Python: 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)] - lsp: 0.42.0 (<module 'robotframework_ls' from 'c:\\Users\\roberto.baggio\\.vscode\\extensions\\robocorp.robotframework-lsp-0.42.0\\src\\robotframework_ls\\__init__.py'>) - platform: win32 - sys.prefix: C:\Users\roberto.baggio\AppData\Local\Programs\Python\Python37 - sys.executable: C:\Users\roberto.baggio\AppData\Local\Programs\Python\Python37\python.exe

server-api: 2022-03-29 08:38:04 UTC pid: 4740 - MainThread - INFO - robocorp_ls_core.python_ls
Starting RobotFrameworkServerApiWithObserver IO language server. pid: 4740

server-api: 2022-03-29 08:38:05 UTC pid: 4740 - MainThread - INFO - robotframework_ls.impl.libspec_manager
User libspec dir: C:\Users\roberto.baggio\.robotframework-ls\specs\v2\0c540f60_4.1.3\user

server-api: 2022-03-29 08:38:05 UTC pid: 4740 - MainThread - INFO - robotframework_ls.impl.libspec_manager
Builtins libspec dir: C:\Users\roberto.baggio\.robotframework-ls\specs\v2\0c540f60_4.1.3\builtins

server-api: 2022-03-29 08:38:05 UTC pid: 4740 - MainThread - INFO - robotframework_ls.impl.libspec_manager
Cache libspec dir: C:\Users\roberto.baggio\.robotframework-ls\specs\v2\0c540f60_4.1.3\cache

lsp: 2022-03-29 08:39:33 UTC pid: 4164 - MainThread - INFO - robocorp_ls_core.jsonrpc.monitor
Cancelled: Message: id: 13, method: textDocument/hover

lsp: 2022-03-29 08:39:33 UTC pid: 4164 - ThreadPoolExecutor-0_0 - INFO - robotframework_ls.robotframework_ls_impl
Cancelled handling: <function RobotFrameworkLanguageServer._threaded_api_request at 0x000001A60C8AB048>

server-api: 2022-03-29 08:39:33 UTC pid: 20444 - MainThread - INFO - robocorp_ls_core.jsonrpc.monitor
Cancelled: Message: id: 6, method: hover

server-api: 2022-03-29 08:55:39 UTC pid: 4740 - ThreadPoolExecutor-0_10 - INFO - robocorp_ls_core.robotidy_wrapper
Using vendored robotidy

server-api: 2022-03-29 08:55:39 UTC pid: 4740 - ThreadPoolExecutor-0_10 - INFO - robocorp_ls_core.robotidy_wrapper
robotidy module: <module 'robotidy' from 'c:\\Users\\roberto.baggio\\.vscode\\extensions\\robocorp.robotframework-lsp-0.42.0\\src\\robotframework_ls\\vendored\\robocorp_ls_core\\libs\\robotidy_lib\\robotidy\\__init__.py'>

**Comment by fabioz** [comment]
@Franz333 The logs still show you in version `0.42.0`... can you double-check if the issue is in the logs or if you haven't really upgraded to `0.43.0`?

**Comment by Franz333** [comment]
It's very weird..

Look at this printscreen please

![image](https://user-images.githubusercontent.com/15931812/160589913-367481b0-61c7-450a-8792-913e95c14a42.png)

**Comment by fabioz** [comment]
Try to do the following: close vscode / erase the logs / start vscode / reproduce the issue -> check if the new logs are correct.

Also, do you by any chance have any other Robot Framework-related extension installed?

**Comment by Franz333** [comment]
well spotted ! 

First block is what I have in my C:\Users\roberto.baggio
Second block is what I have in my C:\Users\roberto.baggio\.vscode\extensions

Dunno what how it ended up in the first block.. Will ask my sysadmin to remove it and I will let you know..

Thank you

![image](https://user-images.githubusercontent.com/15931812/160602067-e0aa106a-64eb-4644-9d52-db67f9810dfe.png)

**Comment by fabioz** [comment]
As a note, I got another report and it seems that on some cases even `0.43.0` can have the issue.

-- the issue being that the uri sent from VSCode for invalidation is something as `file:///c%3A/some_path`, whereas the internal uri is something as `file:///c:/some_path`.

So, I'll probably do a bugfix release later today with a new fix for this.

**Comment by Franz333** [comment]
Yeah I have that pattern in the URI too.. 
Thank you Fabioz !

**Comment by Franz333** [comment]
For the record...

I had my working dir saved in OneDrive (for double back-up purposes)
It did not create any problem until the bug I opened tough.

After your fix, I still noticed an error showing in the log but the intellisense was working as expected when modifying a keyword (changing name, adding or removing args)

Here is the error in the log (XXX is replacing project brand for privacy)
```
server-api: 2022-03-30 10:18:32 UTC pid: 13556 - ThreadPoolExecutor-0_0 - INFO - robocorp_ls_core.workspace
Unable to load contents from: file:///c:/Users/roberto.baggio/OneDrive%20-%20XXX/Documents/%40XXX/XXX%20Git/XXXX-web-automation/XXX/Lab/bin/__init__.robot
```

Relocating my working dir in the Desktop is solving the problem. No more message in the output logs.
