### ISSUE TITLE
Completion/analysis can crash with wrong resource

### ISSUE THREAD

**Issue by fabioz** [robocorp/robotframework-lsp#63]
If the resource filename points to a directory it can give an exception for code analysis/code completion when collecting keywords.

**Comment by fabioz** [comment]
Error:

```
lsp: 2020-05-05 12:40:31 UTC pid: 8008 - MainThread - EXCEPTION - robotframework_ls.server_api.server
Error collecting errors.Traceback (most recent call last):
  File "c:\Users\elyk7\.vscode\extensions\robocorptech.robotframework-lsp-0.1.0\src\robotframework_ls\cache.py", line 46, in new_func
    return func_cache[args_cache_key]
KeyError: NoneDuring handling of the above exception, another exception occurred:Traceback (most recent call last):
  File "c:\Users\elyk7\.vscode\extensions\robocorptech.robotframework-lsp-0.1.0\src\robotframework_ls\cache.py", line 46, in new_func
    return func_cache[args_cache_key]
KeyError: NoneDuring handling of the above exception, another exception occurred:Traceback (most recent call last):
  File "c:\Users\elyk7\.vscode\extensions\robocorptech.robotframework-lsp-0.1.0\src\robotframework_ls\server_api\server.py", line 85, in m_lint
    errors.extend(code_analysis.collect_analysis_errors(completion_context))
  File "c:\Users\elyk7\.vscode\extensions\robocorptech.robotframework-lsp-0.1.0\src\robotframework_ls\impl\code_analysis.py", line 107, in collect_analysis_errors
    collect_keywords(completion_context, collector)
  File "c:\Users\elyk7\.vscode\extensions\robocorptech.robotframework-lsp-0.1.0\src\robotframework_ls\impl\collect_keywords.py", line 335, in collect_keywords
    _collect_following_imports(completion_context, collector)
  File "c:\Users\elyk7\.vscode\extensions\robocorptech.robotframework-lsp-0.1.0\src\robotframework_ls\impl\collect_keywords.py", line 271, in _collect_following_imports
    _collect_resource_imports_keywords(completion_context, collector)
  File "c:\Users\elyk7\.vscode\extensions\robocorptech.robotframework-lsp-0.1.0\src\robotframework_ls\impl\collect_keywords.py", line 262, in _collect_resource_imports_keywords
    _collect_following_imports(new_ctx, collector)
  File "c:\Users\elyk7\.vscode\extensions\robocorptech.robotframework-lsp-0.1.0\src\robotframework_ls\impl\collect_keywords.py", line 271, in _collect_following_imports
    _collect_resource_imports_keywords(completion_context, collector)
  File "c:\Users\elyk7\.vscode\extensions\robocorptech.robotframework-lsp-0.1.0\src\robotframework_ls\impl\collect_keywords.py", line 262, in _collect_resource_imports_keywords
    _collect_following_imports(new_ctx, collector)
  File "c:\Users\elyk7\.vscode\extensions\robocorptech.robotframework-lsp-0.1.0\src\robotframework_ls\impl\collect_keywords.py", line 269, in _collect_following_imports
    _collect_current_doc_keywords(completion_context, collector)
  File "c:\Users\elyk7\.vscode\extensions\robocorptech.robotframework-lsp-0.1.0\src\robotframework_ls\impl\collect_keywords.py", line 210, in _collect_current_doc_keywords
    ast = completion_context.get_ast()
  File "c:\Users\elyk7\.vscode\extensions\robocorptech.robotframework-lsp-0.1.0\src\robotframework_ls\cache.py", line 48, in new_func
    ret = func(self, *args, **kwargs)
  File "c:\Users\elyk7\.vscode\extensions\robocorptech.robotframework-lsp-0.1.0\src\robotframework_ls\impl\completion_context.py", line 186, in get_ast
    return self.doc.get_ast()
  File "c:\Users\elyk7\.vscode\extensions\robocorptech.robotframework-lsp-0.1.0\src\robotframework_ls\cache.py", line 48, in new_func
    ret = func(self, *args, **kwargs)
  File "c:\Users\elyk7\.vscode\extensions\robocorptech.robotframework-lsp-0.1.0\src\robotframework_ls\impl\robot_workspace.py", line 77, in get_ast
    source = self.source
  File "c:\Users\elyk7\.vscode\extensions\robocorptech.robotframework-lsp-0.1.0\src\robotframework_ls\workspace.py", line 223, in source
    with io.open(self.path, "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\Users\\elyk7\\develop\\nx\\cloud_portal\\robot_tests\\test-cases\\..\\'
```
