### ISSUE TITLE
WHILE statement breaks flow explorer

### ISSUE THREAD

**Issue by fabioz** [robocorp/robotframework-lsp#742]
A test to reproduce this in `robotframework_ls_tests.test_rf_json_builder.py`:

```
def test_create_build_model_with_while(tmpdir):
    my = tmpdir.join("my.robot")
    my.write_text(
        """
*** Keywords ***
My Keyword
    WHILE  $a>0
        Log    ${a}
    END
""",
        encoding="utf-8",
    )
    from robotframework_ls.impl.rf_model_builder import RFModelBuilder

    output = RFModelBuilder(robot_file_path=str(my)).build()
    # TODO: Check that output is correct...

```

**Comment by fabioz** [comment]
The current traceback for this is:

```
___________________________ test_create_build_model ___________________________
Traceback (most recent call last):
  File "D:\x\vscode-robot\robotframework-lsp\robotframework-ls\tests\robotframework_ls_tests\test_rf_json_builder.py", line 197, in test_create_build_model
    output = RFModelBuilder(robot_file_path=str(my)).build()
  File "D:\x\vscode-robot\robotframework-lsp\robotframework-ls\src\robotframework_ls\impl\rf_model_builder.py", line 497, in build
    model = transformer.parse(suite)
  File "D:\x\vscode-robot\robotframework-lsp\robotframework-ls\src\robotframework_ls\impl\rf_model_builder.py", line 246, in parse
    suite.visit(self)
  File "C:\bin\Miniconda\envs\py_38_tests\lib\site-packages\robot\model\testsuite.py", line 263, in visit
    visitor.visit_suite(self)
  File "C:\bin\Miniconda\envs\py_38_tests\lib\site-packages\robot\model\visitor.py", line 94, in visit_suite
    if self.start_suite(suite) is not False:
  File "D:\x\vscode-robot\robotframework-lsp\robotframework-ls\src\robotframework_ls\impl\rf_model_builder.py", line 256, in start_suite
    keywords = [
  File "D:\x\vscode-robot\robotframework-lsp\robotframework-ls\src\robotframework_ls\impl\rf_model_builder.py", line 257, in <listcomp>
    KeywordModelParser().parse(kw) for kw in suite.resource.keywords
  File "D:\x\vscode-robot\robotframework-lsp\robotframework-ls\src\robotframework_ls\impl\rf_model_builder.py", line 232, in parse
    keyword.body.visit(self)
  File "C:\bin\Miniconda\envs\py_38_tests\lib\site-packages\robot\model\itemlist.py", line 65, in visit
    item.visit(visitor)
  File "C:\bin\Miniconda\envs\py_38_tests\lib\site-packages\robot\model\control.py", line 76, in visit
    visitor.visit_while(self)
  File "C:\bin\Miniconda\envs\py_38_tests\lib\site-packages\robot\model\visitor.py", line 334, in visit_while
    if self.start_while(while_) is not False:
  File "D:\x\vscode-robot\robotframework-lsp\robotframework-ls\src\robotframework_ls\impl\rf_model_builder.py", line 196, in start_while
    "flavor": while_.flavor,
AttributeError: 'While' object has no attribute 'flavor'
```

**Comment by fabioz** [comment]
Closing this one (as we're doing a major revamp in the area).
