### ISSUE TITLE
Error during activation of Robocorp Code

### ISSUE THREAD

**Issue by mukhay** [robocorp/robotframework-lsp#752]
**Describe the bug**
After installing all necessary packages, I am getting an error when I tried to do the “Robocorp: Create Robot” as mentioned in the tutorial https://robocorp.com/docs/courses/beginners-course/set-up-robocorp-lab

**To Reproduce**
I 've tried to do the “Robocorp: Create Robot” as mentioned in the tutorial https://robocorp.com/docs/courses/beginners-course/set-up-robocorp-lab

**Error**
```
Activating Robocorp Code extension.
Waiting for Robocorp Code (python) language server to finish activating...
Downloading from: https://downloads.robocorp.com/rcc/releases/v11.14.5/linux32/rcc
Downloaded: 0.0MB of NaNMB (NaN%)
Error downloading (0 of 3). Error: undefined
Attempt: 2 - Downloaded: 0.0MB of NaNMB (NaN%)
Error downloading (1 of 3). Error: undefined
Error downloading (2 of 3). Error: undefined
ROBOCORP_HOME: /home/admin/.robocorp
Executing: /home/admin/.vscode/extensions/robocorp.robocorp-code-0.36.0/bin/rcc configure diagnostics -j --controller RobocorpCode
Error executing: /home/admin/.vscode/extensions/robocorp.robocorp-code-0.36.0/bin/rcc configure diagnostics -j --controller RobocorpCode
Error code: undefined
Error: error
Error getting RCC diagnostics.
There was an error getting RCC diagnostics. Robocorp Code will not be started!
Robocorp Code extension disabled. Reason: Unable to get python to launch language server.
Unable to activate Robocorp Code extension because python executable from RCC environment was not provided.
 -- Most common reason is that the environment couldn't be created due to network connectivity issues.
 -- Please fix the error and restart VSCode.
Error getting Python
    Unable to get language server python info.
    Error: Unable to get language server python info.
    	at /home/admin/.vscode/extensions/robocorp.robocorp-code-0.36.0/vscode-client/out/extension.js:89:23
    	at Generator.next (<anonymous>)
    	at fulfilled (/home/admin/.vscode/extensions/robocorp.robocorp-code-0.36.0/vscode-client/out/extension.js:23:58)
    	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[Error - 2:11:11 PM] Starting client failed
Error: Unable to get language server python info.
	at /home/admin/.vscode/extensions/robocorp.robocorp-code-0.36.0/vscode-client/out/extension.js:89:23
	at Generator.next (<anonymous>)
	at fulfilled (/home/admin/.vscode/extensions/robocorp.robocorp-code-0.36.0/vscode-client/out/extension.js:23:58)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
Error initializing Robocorp code.
    Unable to get language server python info.
    Error: Unable to get language server python info.
    	at /home/admin/.vscode/extensions/robocorp.robocorp-code-0.36.0/vscode-client/out/extension.js:89:23
    	at Generator.next (<anonymous>)
    	at fulfilled (/home/admin/.vscode/extensions/robocorp.robocorp-code-0.36.0/vscode-client/out/extension.js:23:58)
    	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
Robocorp Code initialization finished. Took: 1.5s
Downloading from: https://downloads.robocorp.com/rcc/releases/v11.14.5/linux32/rcc
Downloading from: https://downloads.robocorp.com/rcc/releases/v11.14.5/linux32/rcc
Downloading from: https://downloads.robocorp.com/rcc/releases/v11.14.5/linux32/rcc
Downloading from: https://downloads.robocorp.com/rcc/releases/v11.14.5/linux32/rcc
Downloading from: https://downloads.robocorp.com/rcc/releases/v11.14.5/linux32/rcc
Downloaded: 0.0MB of NaNMB (NaN%)
Error downloading (0 of 3). Error: undefined
Downloaded: 0.0MB of NaNMB (NaN%)
Error downloading (0 of 3). Error: undefined
Downloaded: 0.0MB of NaNMB (NaN%)
Error downloading (0 of 3). Error: undefined
Downloaded: 0.0MB of NaNMB (NaN%)
Error downloading (0 of 3). Error: undefined
Downloaded: 0.0MB of NaNMB (NaN%)
Error downloading (0 of 3). Error: undefined
Attempt: 2 - Downloaded: 0.0MB of NaNMB (NaN%)
Error downloading (1 of 3). Error: undefined
Attempt: 2 - Downloaded: 0.0MB of NaNMB (NaN%)
Error downloading (1 of 3). Error: undefined
Attempt: 3 - Downloaded: 0.0MB of NaNMB (NaN%)
Error downloading (2 of 3). Error: undefined
Error executing: /home/admin/.vscode/extensions/robocorp.robocorp-code-0.36.0/bin/rcc feedback metric -t vscode -n vscode.code.error -v RCC_DIAGNOSTICS
Error code: undefined
Error: error
Attempt: 2 - Downloaded: 0.0MB of NaNMB (NaN%)
Error downloading (1 of 3). Error: undefined
Attempt: 2 - Downloaded: 0.0MB of NaNMB (NaN%)
Error downloading (1 of 3). Error: undefined
Attempt: 2 - Downloaded: 0.0MB of NaNMB (NaN%)
Error downloading (1 of 3). Error: undefined
Attempt: 3 - Downloaded: 0.0MB of NaNMB (NaN%)
Error downloading (2 of 3). Error: undefined
Error executing: /home/admin/.vscode/extensions/robocorp.robocorp-code-0.36.0/bin/rcc feedback metric -t vscode -n vscode.code.error -v INIT_NO_PYTHON_LANGUAGE_SERVER
Error code: undefined
Error: error
Error downloading (2 of 3). Error: undefined
Error executing: /home/admin/.vscode/extensions/robocorp.robocorp-code-0.36.0/bin/rcc feedback metric -t vscode -n vscode.code.error -v INIT_PYTHON_ERR
Error code: undefined
Error: error
Attempt: 3 - Downloaded: 0.0MB of NaNMB (NaN%)
Error downloading (2 of 3). Error: undefined
Error executing: /home/admin/.vscode/extensions/robocorp.robocorp-code-0.36.0/bin/rcc feedback metric -t vscode -n vscode.code.error -v INIT_NO_RCC_DIAGNOSTICS
Error code: undefined
Error: error
Attempt: 3 - Downloaded: 0.0MB of NaNMB (NaN%)
Error downloading (2 of 3). Error: undefined
Error executing: /home/admin/.vscode/extensions/robocorp.robocorp-code-0.36.0/bin/rcc feedback metric -t vscode -n vscode.code.error -v ERROR_INITIALIZING_ROBOCORP_CODE_LANG_SERVER
Error code: undefined
Error: error


**Versions:**
 - OS: Fresh Raspbery Pi 4B x64
 - Robocorp Code 0.36.0
 - Robot Framework Language Server Version: [1.1.0]
 - Client Version: [VSCode 1.71]
```

**Comment by fabioz** [comment]
It seems that the extension isn't able to access the network to download what's needed... do you have some active proxy or firewall?
