### ISSUE TITLE
IllegalArgumentException(s) at 1.1.0 with at least with IntelliJ 2022.2.1 and 2022.2.2 RC

### ISSUE THREAD

**Issue by pekkla** [robocorp/robotframework-lsp#755]
When using any source code navigation at ".resource" or ".robot" files, the plugin causes an exception:

`java.lang.IllegalArgumentException: URI has an authority component
	at java.base/java.io.File.<init>(File.java:425)
	at robocorp.lsp.intellij.Uris.toFile(Uris.java:41)
	at robocorp.lsp.intellij.FeatureDefinition.resolve(FeatureDefinition.java:112)
	at robocorp.lsp.psi.LSPPsiAstElement$LSPReference.resolve(LSPPsiAstElement.java:35)
	at com.intellij.codeInsight.TargetElementUtil.getTargetCandidates(TargetElementUtil.java:222)
	at com.intellij.model.psi.impl.TargetsKt.fromTargetEvaluator(targets.kt:176)
	at com.intellij.model.psi.impl.TargetsKt.declarationsOrReferences(targets.kt:134)
	at com.intellij.model.psi.impl.TargetsKt.declaredReferencedData(targets.kt:41)
	at com.intellij.codeInsight.navigation.impl.GtduKt.fromTargetData(gtdu.kt:63)
	at com.intellij.codeInsight.navigation.impl.GtduKt.gotoDeclarationOrUsagesInner(gtdu.kt:59)
	at com.intellij.codeInsight.navigation.impl.GtduKt.access$gotoDeclarationOrUsagesInner(gtdu.kt:1)
	at com.intellij.codeInsight.navigation.impl.GtduKt$gotoDeclarationOrUsages$1.invoke(gtdu.kt:20)
	at com.intellij.codeInsight.navigation.impl.GtduKt$gotoDeclarationOrUsages$1.invoke(gtdu.kt)
	at com.intellij.codeInsight.navigation.impl.CommonKt.fromHostFile(common.kt:21)
	at com.intellij.codeInsight.navigation.impl.CommonKt.processInjectionThenHost(common.kt:15)
	at com.intellij.codeInsight.navigation.impl.GtduKt.gotoDeclarationOrUsages(gtdu.kt:20)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationOrUsageHandler2.gotoDeclarationOrUsages(GotoDeclarationOrUsageHandler2.kt:31)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationOrUsageHandler2.access$gotoDeclarationOrUsages(GotoDeclarationOrUsageHandler2.kt:25)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationOrUsageHandler2$invoke$actionResult$1.compute(GotoDeclarationOrUsageHandler2.kt:61)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationOrUsageHandler2$invoke$actionResult$1.compute(GotoDeclarationOrUsageHandler2.kt:25)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:928)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$underModalProgress$1(ActionUtil.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$underModalProgress$2(ActionUtil.java:236)
	at com.intellij.openapi.progress.impl.CoreProgressManager$1.run(CoreProgressManager.java:270)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$8(CoreProgressManager.java:526)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:84)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
`

**Comment by fabioz** [comment]
@pekkla I can't really reproduce this (presumably the URI is not being generated correctly in your use case, but it works in general as it's working in my machine and there are no other reports about it). 

Can you provide the logging when this happens? 
See: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/reporting_issues.md#intellij-logs for details on how to collect the logs.

I plan to do a release today, so, if you're able to provide the logs soon I may be able to include a fix along with it...

**Comment by pekkla** [comment]
Ok - I will search for the logs.

**Comment by fabioz** [comment]
> Here are the logs from the custom path ROBOTFRAMEWORK_LS_LOG_FILE=<path/to/robotframework_ls.log> after reproducing a couple of errors:
> [robot_ls.zip](https://github.com/robocorp/robotframework-lsp/files/9564583/robot_ls.zip)

It seems the logs didn't make it (the .zip seems to be empty). Can you double check?

**Comment by pekkla** [comment]
[idea.log](https://github.com/robocorp/robotframework-lsp/files/9572032/idea.log)

**Comment by pekkla** [comment]
[robotframework_ls.lsp.134624.log](https://github.com/robocorp/robotframework-lsp/files/9572052/robotframework_ls.lsp.134624.log)

**Comment by fabioz** [comment]
It seems that the real issue is that the URI for the files accessed from a WSL container don't map properly to a filepath when doing the roundtrip.

The uris are something as:

Received URIs are in the format:
`file:////wsl$/Ubuntu/home/lauri/git/newgit/test-framework/robot-tests/tests/templates/fault_sequence_detector.resource`

It seems internally it also finds it with:
`file://wsl%24/Ubuntu/home/lauri/git/newgit/test-framework/robot-tests/keywords/iot_message_keywords.resource`

I need to investigate a bit more how to work with that use-case...
