### ISSUE TITLE
Vs Code doesnt launch Robocorp Code

### ISSUE THREAD

**Issue by IrinaNorro** [robocorp/robotframework-lsp#767]
Hi, 
1) I installed VS code with extensions 1)Robocorp Code and 2)Robot Framework Language Server.
2) Then I tried to create first robot, and Error pops out
"Enable to activate Robocorp Code extension" 
Also error about long path names shows up every time, but I resolved that issue. I have started computer again and I have uninstalled and reinstalled VSCode, and both extensions. I have also installed Robot Framework on my computer. I am not sure if cmd.exe is the problem, i am the only and main user of this computer. This error still occurs: "Long path support failed. Reason: exec: "cmd.exe": executable file not found in %PATH%"
When checking Robot Framework version on Command Line, it says:
"Robot Framework 5.0.1 (Python 3.10.3 on win32)" My Windows is 64 bit, is this a problem?

Best Regards Irina
Hope you can help me, I really want to start coding robots.

**Comment by IrinaNorro** [comment]
Actually i checked that my Windows is 64. And when checking python version it says:

Python 3.10.3 (tags/v3.10.3:a342a49, Mar 16 2022, 13:07:40) [MSC v.1929 64 bit (AMD64)] on win32

**Comment by fabioz** [comment]
Hello @IrinaNorro the extension is probably not starting up properly due to the long path support.

What version of windows are you using? Have you tried following: https://robocorp.com/docs/troubleshooting/windows-long-path

Can you provide the output you have in the View: `OUTPUT`, with `Robocorp Code` selected in the dropdown?

**Comment by IrinaNorro** [comment]
Hi Fabioz,
Thank you for your message.
I have WIndows 10.
Yes I have solved issue concerning long path wit. Now it is in order. I have also checked that in RegistryEditor variable is 1 and not 0. The error message about long path still pops up.

This message is in Output:
Activating Robocorp Code extension.
Waiting for Robocorp Code (python) language server to finish activating...
Executing: c:\Users\Omistaja\.vscode\extensions\robocorp.robocorp-code-0.37.0\bin\rcc.exe configure longpaths
Error executing: c:\Users\Omistaja\.vscode\extensions\robocorp.robocorp-code-0.37.0\bin\rcc.exe configure longpaths
Error code: undefined
Error: error
Stderr: WARNING!  Long path support failed. Reason: exec: "cmd.exe": executable file not found in %PATH%.
WARNING!  See https://robocorp.com/docs/product-manuals/robocorp-lab/troubleshooting#windows-has-to-have-long-filenames-support-on for more details.
Long paths do not work!

Windows long paths support NOT enabled.
Extension will not be activated because Windows long paths support not enabled.
Robocorp Code extension disabled. Reason: Unable to get python to launch language server.
Unable to activate Robocorp Code extension because python executable from RCC environment was not provided.
 -- Most common reason is that the environment couldn't be created due to network connectivity issues.
 -- Please fix the error and restart VSCode.
Error getting Python
    Unable to get language server python info.
    Error: Unable to get language server python info.
    	at c:\Users\Omistaja\.vscode\extensions\robocorp.robocorp-code-0.37.0\vscode-client\out\extension.js:90:23
    	at Generator.next (<anonymous>)
    	at fulfilled (c:\Users\Omistaja\.vscode\extensions\robocorp.robocorp-code-0.37.0\vscode-client\out\extension.js:23:58)
    	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[Error - 21.02.08] Starting client failed
Error: Unable to get language server python info.
	at c:\Users\Omistaja\.vscode\extensions\robocorp.robocorp-code-0.37.0\vscode-client\out\extension.js:90:23
	at Generator.next (<anonymous>)
	at fulfilled (c:\Users\Omistaja\.vscode\extensions\robocorp.robocorp-code-0.37.0\vscode-client\out\extension.js:23:58)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
Error initializing Robocorp code.
    Unable to get language server python info.
    Error: Unable to get language server python info.
    	at c:\Users\Omistaja\.vscode\extensions\robocorp.robocorp-code-0.37.0\vscode-client\out\extension.js:90:23
    	at Generator.next (<anonymous>)
    	at fulfilled (c:\Users\Omistaja\.vscode\extensions\robocorp.robocorp-code-0.37.0\vscode-client\out\extension.js:23:58)
    	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
Robocorp Code initialization finished. Took: 3.5s
ROBOCORP_HOME: C:\Users\Omistaja\AppData\Local\robocorp
Error executing: c:\Users\Omistaja\.vscode\extensions\robocorp.robocorp-code-0.37.0\bin\rcc.exe feedback metric -t vscode -n vscode.code.error -v INIT_NO_LONGPATH_SUPPORT
Error code: undefined
Error: error
Stderr: Tracking is disabled. Quitting.

Error executing: c:\Users\Omistaja\.vscode\extensions\robocorp.robocorp-code-0.37.0\bin\rcc.exe feedback metric -t vscode -n vscode.code.error -v INIT_PYTHON_ERR
Error code: undefined
Error: error
Stderr: Tracking is disabled. Quitting.

Error executing: c:\Users\Omistaja\.vscode\extensions\robocorp.robocorp-code-0.37.0\bin\rcc.exe feedback metric -t vscode -n vscode.code.error -v INIT_NO_PYTHON_LANGUAGE_SERVER
Error code: undefined
Error: error
Stderr: Tracking is disabled. Quitting.

Error executing: c:\Users\Omistaja\.vscode\extensions\robocorp.robocorp-code-0.37.0\bin\rcc.exe feedback metric -t vscode -n vscode.code.error -v ERROR_INITIALIZING_ROBOCORP_CODE_LANG_SERVER
Error code: undefined
Error: error
Stderr: Tracking is disabled. Quitting.

**Comment by fabioz** [comment]
@vjmp @kariharju do you know what could be the problem here?

@IrinaNorro can you check if your Windows version is a supported version (i.e.: https://robocorp.com/docs/troubleshooting/development-system-requirements)

**Comment by IrinaNorro** [comment]
Yes I have 
WIndows 10 Pro
Version 10.0.19043 Build 19043

I cannot find info on Server version.

**Comment by fabioz** [comment]
One thing that you can do as a workaround is setting an environment variable:

`ROBOCORP_OVERRIDE_SYSTEM_REQUIREMENTS=1`

This will make it skip those checks (it's not ideal, but it can be used as a workaround).

Note: you have to set that in the system and restart VSCode so that it picks up that environment variable.

**Comment by IrinaNorro** [comment]
Hi, 
yes it seems like workaround trick worked out. I managed to run example robot and it seems working now. 
Thankyou for your help. 
Irina
