### ISSUE TITLE
Can't convert simple UIPath process into Robocorp format

### ISSUE THREAD

**Issue by sergiolib** [robocorp/robotframework-lsp#886]
**Describe the bug**
I created a small UIPath project through their demo online Studio version which only makes a few clicks on webpages. When using the VSCode extension to convert the exported project from UIPath into Robocorp/Robot Framwork, the converter fails and no files get created.

The traceback is a follows:
```
Error making conversion.
    Unexpected token ﻿ in JSON at position 0
    SyntaxError: Unexpected token ﻿ in JSON at position 0
        at JSON.parse (<anonymous>)
        at t.FileSystemUiPathProject.getProjectJson (/home/sliberman/.vscode/extensions/robocorp.robocorp-code-1.1.3/vscode-client/out/converter-with-commons/bundle.js:2:636377)
        at /home/sliberman/.vscode/extensions/robocorp.robocorp-code-1.1.3/vscode-client/out/converter-with-commons/bundle.js:2:582714
        at Array.reduce (<anonymous>)
        at /home/sliberman/.vscode/extensions/robocorp.robocorp-code-1.1.3/vscode-client/out/converter-with-commons/bundle.js:2:582682
        at Object.t.generateSchema (/home/sliberman/.vscode/extensions/robocorp.robocorp-code-1.1.3/vscode-client/out/converter-with-commons/bundle.js:2:582841)
        at Object.t.main (/home/sliberman/.vscode/extensions/robocorp.robocorp-code-1.1.3/vscode-client/out/converter-with-commons/bundle.js:2:485973)
        at /home/sliberman/.vscode/extensions/robocorp.robocorp-code-1.1.3/vscode-client/src/conversion.ts:50:34
        at Generator.next (<anonymous>)
        at /home/sliberman/.vscode/extensions/robocorp.robocorp-code-1.1.3/vscode-client/out/conversion.js:8:71
        at new Promise (<anonymous>)
        at __awaiter (/home/sliberman/.vscode/extensions/robocorp.robocorp-code-1.1.3/vscode-client/out/conversion.js:4:12)
        at conversionMain (/home/sliberman/.vscode/extensions/robocorp.robocorp-code-1.1.3/vscode-client/out/conversion.js:41:12)
        at /home/sliberman/.vscode/extensions/robocorp.robocorp-code-1.1.3/vscode-client/src/conversion.ts:428:70
        at Generator.next (<anonymous>)
        at fulfilled (/home/sliberman/.vscode/extensions/robocorp.robocorp-code-1.1.3/vscode-client/out/conversion.js:5:58)
```

**To Reproduce**
1. Logged in into UIPath online studio and created robot.
2. Went into "projects" view -> settings -> download project. The created ZIP's content can be found [in this repo](https://github.com/sergiolib/test-uipath-process).
3. Create project from the basic robot framework template and opened folder as current workspace
5. Open the conversion accelerator, select UIPath. Select the output folder to be the workspace folder
6. Press convert to Robot and obtain the traceback above in the console

**Expected behavior**
It should have created the robot files in the open project folder without an error.

**Screenshots**
![image](https://user-images.githubusercontent.com/6540269/218701744-4d7531e4-f3c8-4796-9433-7d6b7fa44b07.png)
![image](https://user-images.githubusercontent.com/6540269/218701832-2533481b-9a8e-4168-88f0-b2179df193f6.png)
![image](https://user-images.githubusercontent.com/6540269/218701915-bf0641ea-6ef5-4b9c-8767-57b8139c473b.png)

**Versions:**
 - OS: Fedora Linux 37 (Workstation Edition) x86_64
 - Robot Framework Version: 5.0.1
 - Robot Framework Language Server Version: V1.9.0
 - Client Version: VSCode 1.75.1 (Robocorp Code V1.1.3)

**Comment by sergiolib** [comment]
@etusien

**Comment by fabioz** [comment]
@mstn something to verify in the converter...

**Comment by mstn** [comment]
@sergiolib sorry for the late reply. We improved the migration tool and this error shouldn't happen. Can you please retry? Thanks!

**Comment by sergiolib** [comment]
Hi @mstn 
Thanks for your work. I will try it as soon as I get a minute and let you know!
Best regards!
